### ISSUE TITLE
item dupe bug

### ISSUE THREAD

**Issue by 314resqi** [TeamAOF/All-of-Fabric-3#100]
Hi, i found i way to dupe items with crate - standart from facility. 

1. Use it as a backpack - right-click into air to open it. and write there "ore".
2. these 2 things will happen:
items in crate will be filtered to words containing ore
armor from you character will be striped from you and your inventory will be sorted - "r" in "ore"

3. Then you shift-click ores from crate to your inventory.
4. Change the position of the crate in your hud from its "sorted" position somewhere else - YOU NEED TO CHANGE ITS POSITION OR DUPE WONT HAPPEN
5. do 1 and rinse and repeat for unlimited ore - it should be possible to apply to other items

**Comment by Monster-Zer0** [comment]
please report to facility https://github.com/grondag/facility/issues/23
