### ISSUE TITLE
Armor sort bug

### ISSUE THREAD

**Issue by 314resqi** [TeamAOF/All-of-Fabric-3#101]
Hi, if you open crate - standart and write into search field "r", it will STRIP your armor into inventory and sort it.
If you do "r" in inventory it wont strip your armor.

**Comment by Monster-Zer0** [comment]
need more detail please

what crate? in what mod?

**Comment by Monster-Zer0** [comment]
is this the same issue https://github.com/grondag/facility/issues/23

**Comment by 314resqi** [comment]
its similar.. it will only happen if you write "r" into search field.
What kind of mod is used for inventory sorting ? Isnt it bug in that mod ?

**Comment by 314resqi** [comment]
About that sorting mod, its also causing issues in #100 ....
i will try to reproduce both these issues with just facility mod

**Comment by 314resqi** [comment]
I cant verify that... i have some other issues...
I can launch mc with fabric 0.9.0 build 204 but with 0.9.1 build 205, 0.9.2 build 206, 0.9.3 build 207 mc just crashes.
I need 0.9.1 and higher to use facility...
