### ISSUE TITLE
EZPAZ item filters crashes server

### ISSUE THREAD

**Issue by SnappierSoap318** [TeamAOF/All-of-Fabric-3#103]
Reproducing steps:
1. add items to filter
2. add the item in filter to a chest connected to a puller
3. the server crashes 
[The Crash](https://imgur.com/a/2ZrKEOc)

**Comment by Monster-Zer0** [comment]
Got a log?

**Comment by SnappierSoap318** [comment]
i crashed the official server so i couldnt get the log

**Comment by Monster-Zer0** [comment]
which official server?

**Comment by SnappierSoap318** [comment]
EU server

**Comment by Monster-Zer0** [comment]
still issue on latest version?

**Comment by SnappierSoap318** [comment]
it doesnt crash the server so i guess its fixed
