### ISSUE TITLE
Cant Join Official AOF3 EU server

### ISSUE THREAD

**Issue by k3nw4y** [TeamAOF/All-of-Fabric-3#105]
Error When joining the EU server
`[13:25:35] [REI-SyncRecipes/ERROR]: roughlyenoughresources:rer_plugin plugin failed to register-displays!
java.lang.NullPointerException: null`
I think this causes the issue, full log on below
https://gist.github.com/k3nw4y/9abf48b4ff70f68f85c40f409fbce0ff

**Comment by Monster-Zer0** [comment]
you need to update to latest AOF version
