### ISSUE TITLE
My game won't launch

### ISSUE THREAD

**Issue by wes1327** [TeamAOF/All-of-Fabric-3#106]
Just downloaded from the twitch launcher, version 2.0.3. Launched Minecraft, and it gives me an error when launching the game, I have not messed with any game files, just downloaded and launched.
![Minecraft](https://user-images.githubusercontent.com/21226310/92996030-4bcb1300-f4d6-11ea-8868-4942a6f79a91.png)

**Comment by Monster-Zer0** [comment]
if you dl from twitch launcher.. then launch from twitch launcher

**Comment by wes1327** [comment]
It was downloaded, and launched from twitch, apparently it was the "latest build" probably a beta, so I went to the stable version and it launched just fine.
