### ISSUE TITLE
Quest not completing when crafting the cooler.

### ISSUE THREAD

**Issue by Allycaz** [TeamAOF/All-of-Fabric-3#110]
Crafting the cooler quest will not complete when crafted, even though it is in my hotbar.
I even tried putting food in it, but still won't complete.

![2020-09-13_22 18 50](https://user-images.githubusercontent.com/71277292/93106495-3efe1900-f6a8-11ea-8182-7bd92b566008.png)

**Comment by Monster-Zer0** [comment]
I think Kibe changed some things when it comes to identifying items. Gotta switch to fuzzy detection in the quest.

**Comment by Monster-Zer0** [comment]
Fixed in dev
