### ISSUE TITLE
Enter Nether and server crashes

### ISSUE THREAD

**Issue by cablerunner** [TeamAOF/All-of-Fabric-3#112]
We entered the nether via portal and server crash. See crash report below..

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/14/20, 11:12 PM
Description: Exception generating new chunk

java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3785.method_16631(class_3785.java:131)
	at net.minecraft.class_3778.method_30419(class_3778.java:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.pieces.GeneralJigsawGenerator.addPieces(GeneralJigsawGenerator.java:23)
	at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.init(TempleNetherStructure.java:37)
	at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.method_16655(TempleNetherStructure.java:30)
	at net.minecraft.class_3195.method_28657(class_3195.java:261)
	at net.minecraft.class_5312.method_28622(class_5312.java:35)
	at net.minecraft.class_2794.method_28508(class_2794.java:278)
	at net.minecraft.class_2794.method_16129(class_2794.java:267)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3785.method_16631(class_3785.java:131)
	at net.minecraft.class_3778.method_30419(class_3778.java:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.pieces.GeneralJigsawGenerator.addPieces(GeneralJigsawGenerator.java:23)
	at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.init(TempleNetherStructure.java:37)
	at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.method_16655(TempleNetherStructure.java:30)
	at net.minecraft.class_3195.method_28657(class_3195.java:261)
	at net.minecraft.class_5312.method_28622(class_5312.java:35)
	at net.minecraft.class_2794.method_28508(class_2794.java:278)
	at net.minecraft.class_2794.method_16129(class_2794.java:267)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: 2,-21
	Position hash: -90194313214
	Generator: net.minecraft.class_3754@67852777
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)

-- Affected level --
Details:
	All players: 1 total; [class_3222['CableRunner'/180, l='ServerLevel[world]', x=-13.96, y=69.00, z=-6.79]]
	Chunk stats: ServerChunkCache: 1833
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-134,65,-71), Chunk: (at 10,4,9 in -9,-5; contains blocks -144,0,-80 to -129,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1783896 game time, 213954 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 72355 (now: false), thunder time: 133276 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:303)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 4.19.0-10-cloud-amd64
	Java Version: 11.0.8, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 3586046952 bytes (3419 MB) / 4874829824 bytes (4649 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 4
	JVM Flags: 1 total; -Xmx7168M
	Fabric Mods: 
		adorn: Adorn 1.11.0+1.16.2
		adventurez: AdventureZ 1.0.10
		allure: Allure 1.2.6
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.9
		artifice: Artifice 0.13.1+1.16.2-rc1
		astromine: Astromine 1.10.4+fabric-1.16.2
		astromine-core: Astromine: Core 1.10.4+fabric-1.16.2
		astromine-discoveries: Astromine: Discoveries 1.10.4+fabric-1.16.2
		astromine-foundations: Astromine: Foundations 1.10.4+fabric-1.16.2
		astromine-technologies: Astromine: Technologies 1.10.4+fabric-1.16.2
		astromine-transportations: Astromine: Transportations 1.10.4+fabric-1.16.2
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bambootweaks: Bamboo Tweaks unspecified
		bedspreads: Bedspreads 1.1.0-1.16.2
		blade: Blade 1.0.1
		blockus: Blockus 1.6.3.2
		blue_endless_jankson: jankson +
		byg: BYG 1.0.7
		campanion: Campanion 1.2.0+build.39
		cardinal-components: Cardinal Components API 2.6.0
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-block: Cardinal Components API (blocks) 2.6.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-level: Cardinal Components API (world saves) 2.6.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		cavebiomes: Cave Biomes 0.3.0
		ce_foodstuffs: Common Expansion: Foodstuffs 1.0.1
		chainmail: Chainmail 0.5.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.0
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.8
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.8
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.1
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		cloth-utils-v1: Cloth Utils v1 1.4.8
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.1
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.0.7
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		crookedcrooks: Crooked Crooks 1.3.0+1.16.3
		crusade: Crusade 1.1.4+1.16.2
		dankstorage: Dank Storage 1.7-1.16.2
		diggusmaximus: Diggus Maximus 1.3.1-1.16
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta1
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		eggtab: Egg Tab 1.3.0+1.16-fabric
		endreborn: End: Rebellion 1.8
		expandedstorage: ExpandedStorage 5.6.26
		ezpas: Ezpas 1.2.2-1.16.2
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.1
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		fallflyinglib: FallFlyingLib 1.1.0
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-2
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.1.2
		gameinfo: GameInfo 2.0.0a-experimental-06.1 1.16.2
		givemehats: Give Me Hats! 1.2.8
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		goml: Get Off My Lawn 1.1.0
		hard-hat-steve: Hard Hat Steve 1.1.1
		hardcorequesting: Hardcore Questing Mode 0.3.1
		harvest: Harvest 1.2.12
		hctm-base: HCTM Base 3.4.0
		horseinfo: Horse Info 0.2.2-1.16.1
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.6.6-BETA
		inmis: Inmis 1.3.0-1.16.2
		inventorysorter: Inventory Sorter 1.7.2-1.16
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.1+j1.2.0
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.0.1
		kibe: Kibe 1.4.2-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1.4.5
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes_core: LibBlockAttributes (Core) 0.8.2-pre.6
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2-pre.6
		libblockattributes_items: LibBlockAttributes (Items) 0.8.2-pre.6
		libcd: LibCapableData 2.5.0+1.16.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		linkart: Linkart unspecified
		lithium: Lithium 0.5.4
		magna: Magna 1.4.2-1.16.2
		mambience: MAmbience 2.1.0+1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		mcdict: MCDict 1.0.0+1.16.2
		minecraft: Minecraft 1.16.2
		mm: Manningham Mills 2.0
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		packages: Packages 1.1
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-40-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.1
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.6-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.4.1+build.69
		repurposed_structures: Repurposed Structures 1.16.2-1.5.4
		respawnablepets: Respawnable Pets 6
		rgbable: RGBable 1.0.0
		ringsofascension: Rings of Ascension 1.0.7
		roughlyenoughitems: Roughly Enough Items 5.4.2
		roughlyenoughitems-api: REI (API) 5.4.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.4.2
		roughlyenoughitems-runtime: REI (Runtime) 5.4.2
		roughlyenoughresources: Roughly Enough Resources 2.1.1
		rswires: RSWires 4.9.1
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		sandwichable: Sandwichable 1.1.2
		secretrooms: Secret Rooms 0.9.2+1.16.2
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tootip 2.1.1+1.16.2
		simpleteleporters: Simple Teleporters 2.2.1
		slabhelper: Slab Helper 1.3.4
		smootherbedrock: Smoother Bedrock 1.0.0
		staffofbuilding: Staff of Building 1.2.2-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structure-helpers: Structure Helpers 3.0.0
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.5.3+build.115
		tis3d: TIS-3D 1.5.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trapexpansion: Trap Expansion 1.3.2
		trees-do-not-float: Trees Do Not Float 1.12.94
		trinkets: Trinkets 2.6.4
		universalcomponents: Universal Components 0.7.3+1.16.2
		vanilla-hammers: Vanilla Hammers 2.0.8-1.16.2
		vanilladeathchest: VanillaDeathChest 1.16.2-1.11.0.6-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16.2-1.4.0
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.21.0
		xaeroworldmap: Xaero's World Map 1.10.3
		xpstorage: XP Storage 0.4.1+1.16.2
		yosbr: YOSBR 0.1.1
	Player Count: 1 / 10; [class_3222['CableRunner'/180, l='ServerLevel[world]', x=-13.96, y=69.00, z=-6.79]]
	Data Packs: vanilla (incompatible), fabric/adorn, fabric/adventurez, fabric/allure, fabric/appliedenergistics2, fabric/astromine-core, fabric/astromine-discoveries, fabric/astromine-foundations, fabric/astromine-technologies, fabric/astromine-transportations, fabric/bambootweaks, fabric/bedspreads, fabric/blockus (incompatible), fabric/byg, fabric/campanion, fabric/ce_foodstuffs, fabric/compressedblocks, fabric/computercraft (incompatible), fabric/cotton-commons, fabric/crookedcrooks, fabric/crusade, fabric/dankstorage, fabric/dml-refabricated, fabric/dwarfcoal, fabric/endreborn, fabric/expandedstorage, fabric/ezpas, fabric/fabric-furnaces, fabric/fabric-tool-attribute-api-v1, fabric/flonters, fabric/flora-doubling (incompatible), fabric/glassdoor, fabric/glassential, fabric/goml, fabric/hard-hat-steve (incompatible), fabric/hardcorequesting, fabric/harvest, fabric/hctm-base, fabric/improved-stations, fabric/indrev, fabric/inmis, fabric/iron-jetpacks (incompatible), fabric/kibe, fabric/kubejs (incompatible), fabric/libcd, fabric/linkart, fabric/maybe-data, fabric/packages, fabric/repurposed_structures, fabric/respawnablepets, fabric/rswires, fabric/sandwichable, fabric/secretrooms, fabric/simpleteleporters, fabric/slabhelper, fabric/staffofbuilding, fabric/structure-helpers, fabric/tacocraft, fabric/techreborn, fabric/tis3d (incompatible), fabric/trapexpansion, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/villagerhats, fabric/winged, fabric/wolveswitharmor, fabric/woodenhoppers, fabric/xpstorage, global/cotton_generated (incompatible), secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by TelepathicGrunt** [comment]
Have you made a datapack to go with the modpack? Was the modpack put on a server and you started playing on it right after the server created the world for the very first time?

**Comment by cablerunner** [comment]
Plain mudpack out of the box. I noticed there is a new version out so I am upgrading to it right now. Sent from Mail for Windows 10 From: TelepathicGruntSent: Monday, September 14, 2020 7:33 PMTo: TeamAOF/All-of-Fabric-3Cc: cablerunner; AuthorSubject: Re: [TeamAOF/All-of-Fabric-3] Enter Nether and server crashes (#112) Have you made a datapack to go with the modpack? Was the modpack put on a server and you started playing on it right after the server created the world for the very first time?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cablerunner** [comment]
The 2.0.5 upgrade fixed the nether issue. Sent from Mail for Windows 10 From: TelepathicGruntSent: Monday, September 14, 2020 7:33 PMTo: TeamAOF/All-of-Fabric-3Cc: cablerunner; AuthorSubject: Re: [TeamAOF/All-of-Fabric-3] Enter Nether and server crashes (#112) Have you made a datapack to go with the modpack? Was the modpack put on a server and you started playing on it right after the server created the world for the very first time?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
