### ISSUE TITLE
Crafting Ebony Bookshelf yields default oak bookshelf

### ISSUE THREAD

**Issue by HarrySmith2** [TeamAOF/All-of-Fabric-3#113]
When attempting to craft an Ebony Bookshelf, the default bookshelf is selected and crafted instead. 

![6f3adf3e7fb0ff68804d9fa84dbe8be5](https://user-images.githubusercontent.com/33291554/93243066-94592980-f77f-11ea-87bd-b638fddb7f4d.png)

![0ef265a209382fc7ba82c0c6367188cf](https://user-images.githubusercontent.com/33291554/93243171-bf437d80-f77f-11ea-8bbd-f261da2c38e8.png)

**Comment by Monster-Zer0** [comment]
fixed in dev https://github.com/TeamAOF/All-of-Fabric-3/commit/e324ccb6b90561d9bd208d516546c463c67c19df#diff-b37ea45eb5595eab7ddc64c0bdd727b5
