### ISSUE TITLE
Quest book wan't unlock other quests thant Kibe's ones

### ISSUE THREAD

**Issue by XuruDragon** [TeamAOF/All-of-Fabric-3#114]
Hello there,

With my friend, on my server, we have finish the Kibe"s quests available in the questbook, but impossible to unlock futher quest lkike Tech Reborn"s quests etc...

Is the quest not implemented or it's a bug ? 

![Guestbook](https://i.imgur.com/63EY0XA.png)

Thank you

XuruDragon

**Comment by Monster-Zer0** [comment]
That's because the other quests have not been written yet.

**Comment by XuruDragon** [comment]
Ok.

Any idea of when it will be added to the modpack ? 

thank you

**Comment by BO5AMIS** [comment]
Hey I’m doing a let’s play on the mod pack and I just wanted to ask, is there an eta on quests?

**Comment by Monster-Zer0** [comment]
No idea when.

No eta.

When I get time to do them.
