### ISSUE TITLE
(2.0.5 Server+Client) Magnet Quest is broken

### ISSUE THREAD

**Issue by JustHmm** [TeamAOF/All-of-Fabric-3#119]
When you craft magnet (via crafting table, crafting station or pocket crafting table), hqm doesn't detect that you crafted it.  

*For anyone who needs to skip this quest, "/hqm edit" doesn't work on servers so only way to skip this is "/hqm op playername" open that new book you get and shift click to broken quest to force it to complate than delete the book.

**Comment by Monster-Zer0** [comment]
Don't do all that.

Nothing is broken, just nbt tags change. Go to the quest in hqm edit and change to fuzzy matching.

That's what I'll have to do to fix it anyhow.
