### ISSUE TITLE
Game crashes when getting the recipe from jei to table

### ISSUE THREAD

**Issue by Slamicek** [TeamAOF/All-of-Fabric-3#123]
My game crashes at random. Last when i get the recipe from JEI to the crafting table, The recipe was for copper cable. 
The crash log is: 
[crash-2020-09-20_20.30.15-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5252355/crash-2020-09-20_20.30.15-server.txt)

**Comment by Monster-Zer0** [comment]
how to reproduce?

because I can't.

does this still happen?
