### ISSUE TITLE
Glider Quest cannot be completed.

### ISSUE THREAD

**Issue by Chaogomu** [TeamAOF/All-of-Fabric-3#124]
The quest book does not recognize it when you craft a Red Glider for the first chapter Kibe quest.

I've crafted two of them and the quest still reads 0%. I've not yet started crafting the other colors.

It may be of note that I crafted my first red glider before crafting the slime boots.

**Comment by Chaogomu** [comment]
An update, I cannot finish _any_ quests.

https://imgur.com/a/O5N5Mx3

This shows my quest book as it currently stands. I've tried to complete the glider, the magnet, and the golden lasso. None of the crafting was detected. This is on a multiplayer server, so my access to logs is no existent.

**Comment by Monster-Zer0** [comment]
as with all the past quest issues.

it is the same exact problem. nbt detection. need to change detection to fuzzy. done in latest update, which is not released yet.
