### ISSUE TITLE
Industrial Jackhammer dupe bug

### ISSUE THREAD

**Issue by SnappierSoap318** [TeamAOF/All-of-Fabric-3#125]
AOF version: 2.0.5

reproduction:
Put the industrial jackhammer in 3x3 or 5x5 mode, it duplicates the jackhammer upto 25times(9 for the 3x3 mode, 25 for 5x5mode)

**Comment by Monster-Zer0** [comment]
is that the jackhammer from indrev or tr?

**Comment by SnappierSoap318** [comment]
there is only one industrial jackhammer i dont remember it from which mod
