### ISSUE TITLE
Server Crashes When Using JEI To Make Patterns For Some Tech Reborn Items

### ISSUE THREAD

**Issue by Pungwin** [TeamAOF/All-of-Fabric-3#126]
Every once in a while whilst i was trying to set up autocrafting for the max storage unit, the server would crash when i shift click a machine recipe into a pattern. I can't provide any text proof as this happened on Chosen's server which i dont have access to backend.
The few recipes that its happened to was peridot dust and refined iron plates, however im sure it still happens with more.

**Comment by Monster-Zer0** [comment]
version of aof?
