### ISSUE TITLE
Teleporting to or inside the end dimension crashes the game

### ISSUE THREAD

**Issue by Bleuz** [TeamAOF/All-of-Fabric-3#127]
Teleporting to the end via the end portal crashes my server. I also have to forcibly change my player position NBT data to log back in. It is transferring my position to the end but keeping the overworld XYZ coords. If I take the portal then change my NBT position to 0,0 all seems to be good.

[crash-2020-09-24_10.02.32-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5276643/crash-2020-09-24_10.02.32-server.txt)

**Comment by Monster-Zer0** [comment]
I think this might be a BYG issue.. but im not sure, will have to look into it further.

**Comment by BaronNoogie** [comment]
I'm seeing this too. somewhat reassured to see others have similar issues. Here's my crash log to cross reference. looks like it's not the same crashlog info... but happening when I enter the end portal. I am able to reload the file and I end up a few blocks away from entering the portal. 

Let me know if this should be a separate incident issue. 

[crash-2020-09-25_13.41.08-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5284891/crash-2020-09-25_13.41.08-server.txt)

**Comment by TheEssem** [comment]
Getting this same error as well, it definitely seems like a BYG bug

**Comment by CorgiTaco** [comment]
Should be patched here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3065938

**Comment by Bleuz** [comment]
Can confirm that the newest BYG update fixes the issue running AOF3 2.1.1

Thanks!
