### ISSUE TITLE
entering end portal causes crash

### ISSUE THREAD

**Issue by BaronNoogie** [TeamAOF/All-of-Fabric-3#129]
Here's my crash log to cross reference. When I enter the end portal the client crashes. I am able to reload the file and I end up a few blocks away from entering the portal. 

When I bypass the end portal entirely I am able to get to the end without issues. (/execute in the_end run tp player locationcoords) 

[crash-2020-09-25_13.41.08-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5284891/crash-2020-09-25_13.41.08-server.txt)

**Comment by Monster-Zer0** [comment]
something appears to be blocking it. bad world gen?

**Comment by BaronNoogie** [comment]
yeah, must be. I found a workaround by using the TP command and then setting up waypoints so I didn't need to use the portal. Doesn't appear to be happening in other saves/worlds... so probably a non repeatable fluke. This can probably just be closed.
