### ISSUE TITLE
Omni-Tool doesn't drop blocks/items when mining Tech Reborn or Industrial Revolution ores 

### ISSUE THREAD

**Issue by 2haloes** [TeamAOF/All-of-Fabric-3#130]
Hello, 

I have noticed that in AoF3 2.0.3 and  2.1.1, the Omni-tool fails to properly mine all of the Tech Reborn and Industrial Revolution ores.

This issue doesn't occur using the Advanced Drill and all vanilla ores work as expected.

For AoF3 2.1.1, this was tested on a fresh installation on Solus (Linux)

**Comment by 2haloes** [comment]
Small update, it does show on the HUD that the blocks are not harvestable using the Omni-tool, even on Nikolite ore, which has a harvest level of iron while the tool has no problem mining diamond ore.

**Comment by Monster-Zer0** [comment]
omni tool is ae2?
