### ISSUE TITLE
Wooden Bucket quest removes other quests from the book

### ISSUE THREAD

**Issue by Caridmum** [TeamAOF/All-of-Fabric-3#135]
Completing the Easy Buckets quest to craft a Wooden Bucket removes 8 quests relating to tanks and Ultimate Mob Annihilation!! quest entirely from the quest book.

It goes from this:
![2020-09-27_19 16 08](https://user-images.githubusercontent.com/11216708/94384462-797ba300-00f7-11eb-8cf8-696e7665be31.png)
![2020-09-27_19 23 43](https://user-images.githubusercontent.com/11216708/94384396-5bae3e00-00f7-11eb-8a6e-d3d31b2e27f4.png)

To this:
![2020-09-27_19 16 43](https://user-images.githubusercontent.com/11216708/94384480-81d3de00-00f7-11eb-9607-281eb425c02c.png)
![2020-09-27_19 01 39](https://user-images.githubusercontent.com/11216708/94384447-72549500-00f7-11eb-847e-10ebe8526516.png)

**Comment by Monster-Zer0** [comment]
no, this is reverting to old.

we have some quest updates to fix later, but in this instance your book looks like it's competing on which version to use.

dunno where you would be getting old version, but it would be located in your hqm folder.

**Comment by Caridmum** [comment]
just replicated this with a clean 2.1.3 install so, whatever it is, it's included with the current download

**Comment by Caridmum** [comment]
removing '"optionlinks":["a03fa294-19ec-47f0-bd43-490c35fc5a91"]' from the wooden bucket quest in kibe,json seems to solve this
