### ISSUE TITLE
Carrier mod makes sandwiches uncraftable 

### ISSUE THREAD

**Issue by rboys2** [TeamAOF/All-of-Fabric-3#136]
shift right clicking on the sandwich table to complete the sandwich picks up the table instead

**Comment by vegeta897** [comment]
I already opened a PR for this. #132 

You can fix it in your instance by just [editing that config file to look like this](https://github.com/vegeta897/All-of-Fabric-3/blob/patch-1/config/carrier.json).

**Comment by Monster-Zer0** [comment]
this was fixed
