### ISSUE TITLE
Allure Charcoal Blocks not seen as fuel

### ISSUE THREAD

**Issue by MjolnirMouse** [TeamAOF/All-of-Fabric-3#137]
Is it possible to remove the allure charcoal block recipe or change it to only need 8 charcoal since its just a deco block not fuel? You would need to make sure it breaks back down into 8 as well if you went that route. I ask because dwarf coal makes a charcoal block that is fuel but we cannot get to it because it prioritizes the allure recipe.  Using current release 2.1.2

**Comment by AK9Official** [comment]
2.1.2 has it removed?

**Comment by MjolnirMouse** [comment]
The allure charcoal block wasnt seen as fuel in 2.0.5 either so im not sure what the question is

**Comment by AK9Official** [comment]
The allure charcoal block recipe dosen't exist in 2.1.x

**Comment by MjolnirMouse** [comment]
![2020-09-29_07 14 41](https://user-images.githubusercontent.com/44346485/94551742-d5dbe100-0223-11eb-8580-ddc152af98e2.png)
![2020-09-29_07 16 09](https://user-images.githubusercontent.com/44346485/94551744-d6747780-0223-11eb-894a-4c3608c0cd17.png)
attached is my main menu proving 2.1.2 and a screenshot of allure charcoal block in crafting window
