### ISSUE TITLE
Can't load save game - hard crash (possible HQM problem?)

### ISSUE THREAD

**Issue by GDoe5** [TeamAOF/All-of-Fabric-3#139]
Started playing this modpack yesterday. When we load a single player game (to open up to LAN) it crashes back to desktop.

"Description: Exception in server tick loop 
java.lang.NullPointerException: Exception in server tick loop"
https://pastebin.com/d8jCKqJM

Disabling HQM allowed us to load the save file again, so continuing like that for now.
Thanks

**Comment by Monster-Zer0** [comment]
did you try to create a team?

**Comment by GDoe5** [comment]
yes.

**Comment by wirilome** [comment]
I had the same problem on my game. It first crashed when I hosted my kid in a LAN, we switched to him hosting and it worked. 
A couple days later I had a hard crash while exploring (without any LAN) and couldn't launch the game again. I moved the hqm folder from a backup to my game save and it started working again. I'm backuping before each launch now just in case.

**Comment by GDoe5** [comment]
@ImAK9 Hi - sorry to bother you - I was wondering if you closed this because you found a fix? Or not your problem because it's a HQM problem? Thank you

**Comment by ImAK9** [comment]
Closed it due to quests being removed & redone fully this time, it’s also a HQM bug.
