### ISSUE TITLE
Recipe conflict for Crackers

### ISSUE THREAD

**Issue by metalim** [TeamAOF/All-of-Fabric-3#140]
Recipe:
![image](https://user-images.githubusercontent.com/230431/94829024-c66eba80-0412-11eb-83bf-34d775255a37.png)

Actual result:
![image](https://user-images.githubusercontent.com/230431/94829319-0f267380-0413-11eb-9ed7-23ca7061c167.png)

Also, this blocks S'more recipe.

**Comment by wirilome** [comment]
Ah yep, just reported the same on Discord. issue is with Croptopia flour now, but it's the same issue.

**Comment by Technici4n** [comment]
There is a third conflict now, see #206
