### ISSUE TITLE
Bamboo Tweaks has recipe conflicts in it

### ISSUE THREAD

**Issue by MjolnirMouse** [TeamAOF/All-of-Fabric-3#141]
I am not sure what all recipe conflicts it may have but the bamboo block and bamboo door from that mod both have the same recipe. it defaults to the door when trying to use the recipe breaking the ability to make the bamboo fences from the same mod. I know at 1 time there was a mod that added an button in the crafting window to allow you to switch between conflicting recipe outputs if that mod exists for fabric in this version it would be a great addition to the pack

**Comment by Monster-Zer0** [comment]
it was discontinued, so there it will not be included in next iteration. no need to fix then.
