### ISSUE TITLE
Quests not completing

### ISSUE THREAD

**Issue by TheDarkPreacher** [TeamAOF/All-of-Fabric-3#143]
Getting reports from my players that the golden lasso and glider quests are not detecting on the server.

Pack server version 2.1.2

Should I just give them OP HQM books until this issue is fixed or should I update to 2.1.3?

**Comment by scruff-01** [comment]
I updated to 2.1.3 but they are still broken. I haven't had any luck editing or getting OP books.

**Comment by tyrolanuthmatar** [comment]
Same, on latest version and Golden Lasso does not update and no check button to do so.

**Comment by Monster-Zer0** [comment]
you can't just update. you need to wipe all data. look in world folder and make sure when updating your completely remove hqm in config first

**Comment by Monster-Zer0** [comment]
also op books won't help. the quests have been fixed, 100% sure. so it sounds like you are still pulling old data for some unknown reason. we don't make hqm, so I can only give you speculation.

**Comment by 616dustin** [comment]
Running 2.1.3 server and client. Wonder Woman's Day off quest will not complete.

**Comment by Monster-Zer0** [comment]
ok, well I will look at it. thats all I can tell you.

**Comment by tyrolanuthmatar** [comment]
@Monster-Zer0 - Thanks, we appreciate all your work!  If you need a world back up, let me know!

**Comment by Technici4n** [comment]
Quests have been removed from later versions due to issues, and are probably not going to happen until someone ports BQ/FTBQ, so I'm closing this.
