### ISSUE TITLE
when ever i try to open a world after hosting lan it crashes

### ISSUE THREAD

**Issue by gibbert3** [TeamAOF/All-of-Fabric-3#144]
here is the crash report

[crash-2020-10-05_00.01.52-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5325529/crash-2020-10-05_00.01.52-server.txt)

**Comment by micbusin** [comment]
I made a team in the quest book. After restarting the client the game crashed every time i tried to load the saved game. I disabled the "Hardcore Questing Mode" addon, now i can load my saved world again.

**Comment by Monster-Zer0** [comment]
dont make a team in HQM.. please report to HQM https://github.com/shedaniel/HQM/issues

you need to remove anything HQM in your world folder. it might work then.
