### ISSUE TITLE
Balance with Angel Ring and Netherite requirements - Suggestion

### ISSUE THREAD

**Issue by tyrolanuthmatar** [TeamAOF/All-of-Fabric-3#150]
So, I'm not sure if this is more of a pack question/issue or a specific mod issue, but since the pack has updated what requirements it takes to get the Angel Ring, I'll place it here first.

I'm in latest Server Build and working on end game goals.  The Angel Ring requires the following to make:
2 Glitch Ingots
2 Elytra
2 Empty Boosters
1 Block of Univite
1 Interdeminsional SU

This makes sense it needs a lot of end of pack items due to how powerful this ring is and that it should be an end of pack item.  I would consider myself near end of pack on this current version.

My biggest gripe I guess is the expense of how much Netherite is needed and the issue with Ancient Debris spawning in this pack.  Ancient Debris is very very thinned out in the Nether especially with BYG installed.  BYG admits to this and has made some tweaks, but there are some of the biome creations that don't even spawn the stuff (for example, the Achromatopsian Gallery).  I've bounced into a creative world and found not a single Ancient Debris spawn in that biome.  

That and it's smaller percent spawn rate just makes this thing harder considering the amount of Ancient Debris you need to get with no real way of doing so without grinding through Biomes in the Nether and hope that it spawns in that biome on around level 15 y coordinate.

Now, take the fact that the Netherite Jet Pack itself requires the following:
4 Netherite Ingot for the Jetpack itself
6 Netherite Ingot for the Capacitor
4 Netherite Ingot per Netherite Thruster
2 Netherite for each Energy Cell (the full build needing 5 of these)
1 Netherite per Expert Coil (the full build needing 11 of these)

This means in total, the jetpack alone requires 35 Netherite in total to build and then translates to need 140 Ancient Debris.  (this is not including the Ancient Debris you need for the other items to craft for this, such as the Glitch Ingots or the Univite block)

This is fine, because again, this should be an end pack item.  Te problem is the Nether with BYG having such a low turn out to not only an already low percent spawn, but some biomes not even having it, makes this an incredibly long grinding task.  

I guess my suggestion for this would be to add something to either make hunting down Ancient Debris a bit less tedious or upping the spawn rate of them in BYG.  Not sure what would be a good balance.  I agree with the expense of an end game/pack item like this, but need to bring the tedium down a bit (in my humble opinion).  Other people's thoughts?  Suggestions?

**Comment by dandin87** [comment]
\kubejs\server_scripts\balancing.js is where you can modify this or other items for a personal server. Still a good questions for the pack itself as yes that is a lot of ancient debris. Maybe the netherite jetpack can be tweaked to not be so grindy.

**Comment by tyrolanuthmatar** [comment]
I was thinking for pack balance, maybe an xray mod that is locked behind some sort of material build/quest log/etc or something?  Not sure.  That way, you could keep the requirements, but hunting it down wouldn't be near as bad as blindly mining in the Nether for this many Ancient Debris.

**Comment by Monster-Zer0** [comment]
hqm has basic functionality.. nothing that can allow a mod to activate. I think we just keep it simple and maybe devise a better way around this.

**Comment by Rafaeltheraven** [comment]
You can quadruple your Ancient Debris output using the Industrial Revolution ore quadrupling stack. At that point you get 1-1 ancient debris-netherite output (not counting the gold) and so you only need 35 ancient debris to get the netherite jetpack
