### ISSUE TITLE
Trinkets Mod not being loaded

### ISSUE THREAD

**Issue by 616dustin** [TeamAOF/All-of-Fabric-3#151]
Trinkets shows in the mod list, but no recipes are showing in nei. does not show in multiplayer or single player. does it need to be enabled somehow? client and server version 2.1.3

**Comment by dandin87** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension and https://www.curseforge.com/minecraft/mc-mods/give-me-hats both use trinkets slots. 

You might be thinking of https://www.curseforge.com/minecraft/mc-mods/bunch-o-trinkets which was removed. There were issues with the toolbelt and workpack when you died and not being able to recover the items stored in the second inventory. Also many of the trinkets now have a lot of overlap with other mods that provide slightly better/balanced versions. The gluttony amulet could eat much more often than should be possible and so made you very invincible. Kibe adds an auto eat method as does some armors. Winged mod adds things to replace rocket agilet, hard hat steve has an entire armor set for increasing reach, etc. Basically it did not provide anything significant that other mods were not covering.
