### ISSUE TITLE
Update version of true secret rooms to 1.0.2 

### ISSUE THREAD

**Issue by kabadesu** [TeamAOF/All-of-Fabric-3#158]
I'm not sure if mods are version locked in modpacks, so please delete if it always just grabs the latest version when creating a new instance.

tariqk mentioned this in discord 

> one of my kids came to me and said that they think the server crashed. apparently he was trying out the camo ghost blocks and the server went down. wasn't sure what happened, but here's the server crash log: https://pastebin.com/tmhuHj3i

I came across an identical issue on true secret rooms github and it looks like this issue was fixed about 3 hours ago.

https://github.com/LudoCrypt/True-Secret-Rooms/issues/2

**Comment by dandin87** [comment]
mods are version locked. it would be terrible if they were not, because any updated mod could break the pack. Anyways Ludocrypt already informed us about updating their mod.
