### ISSUE TITLE
Received ID map for minecraft:sound_event contains IDs unknown to the receiver!

### ISSUE THREAD

**Issue by NemmieDragon** [TeamAOF/All-of-Fabric-3#161]
I get this error when trying to connect to my server. Both server and client are new installs and new world.
Received ID map for minecraft:sound_event contains IDs unknown to the receiver!
 - ce_foodstuffs:item.tea_bottle.fill
 - ce_foodstuffs:block.kettle.brew

'

**Comment by AK9Official** [comment]
Is this 2.3.0?

**Comment by NemmieDragon** [comment]
I mucked up on the extract
