### ISSUE TITLE
Croptopia crops harvestable anytime after 0%

### ISSUE THREAD

**Issue by kabadesu** [TeamAOF/All-of-Fabric-3#163]
Version 2.3.0

Multiplayer on home server.

Planting croptopia crops then right clicking them immediately to get fully grow crops - which I think sounds different from the current bug in the unreleased changelog.

**Comment by AK9Official** [comment]
Shizzels, I’ll look into it!

**Comment by ExcessiveAmountsOfZombies** [comment]
Which crops was this happening with?

**Comment by kabadesu** [comment]
Oh, my wife retested to clarify. It's not instant, the crop just has to reach a non 0% for it to be harvested. This happened with croptopia corn.
