### ISSUE TITLE
Tech Reborn ores produce Industrial Evolution ingots. Not compatible with recipes.

### ISSUE THREAD

**Issue by Jagnell** [TeamAOF/All-of-Fabric-3#165]
Tech Reborn ores and dusts, when smelted will produce Industrial Evolution ingots. In my experience so far, I have only tried copper, however that is a big enough issue as it is. The issue being: that version of copper that is produced does not work in any other tech recipes that aren't from Industrial Evolution. So it is not possible to even create copper cables and get started in tech reborn.

**Comment by Jagnell** [comment]
I am running the latest version of the pack (2.3.0) on a BisectHosting multiplayer server.

**Comment by AK9Official** [comment]
Update tp 2.3.1

**Comment by Jagnell** [comment]
Is it possible to do so without corrupting the current world?

**Comment by Jagnell** [comment]
Updating from 2.2 to 2.3 destroyed our previous one.

**Comment by Technici4n** [comment]
Updates from 2.3 to later versions should be fine, please open a new issue otherwise.
