### ISSUE TITLE
sodium compatibility

### ISSUE THREAD

**Issue by Armagedon13** [TeamAOF/All-of-Fabric-3#167]
when i try to use sodium in the mod pack, the game crash

https://pastebin.com/EKYVHnEJ

**Comment by Yoosk** [comment]
Sodium is currently not compatible with the pack.

**Comment by Pugzy** [comment]
Can the [wiki page](https://github.com/TeamAOF/All-of-Fabric-3/wiki/Optifine) regarding Optfine be updated to reflect the above?

**Comment by imreallybadatnames** [comment]
GeckoLib makes Sodium crash. If you remove GeckoLib from the `mods` folder, then Sodium will work.

**Comment by kabadesu** [comment]
There's a sodium flavored zip of AOF3 2.5.9 available in the faqs channel of AOF discord too.

**Comment by imreallybadatnames** [comment]
Or just update GeckoLib to the latest version.
