### ISSUE TITLE
Gold Ingot Compression Incompatibility

### ISSUE THREAD

**Issue by danereinsch** [TeamAOF/All-of-Fabric-3#168]
As of right now, the gold plates from tech reborn cannot be made using the forge hammer from Industrial Revolution. This is unfortunate given that many other starting plates for IR are made through that hammer, though are the ones from tech reborn. The gold plates are needed to create the compressor machine from Industrial Revolution, not requiring you to go through the entire Tech Reborn tree to be able to make plates.

**Comment by AK9Official** [comment]
Entire TR tree? All you literally need is the TR Compressor & Generator?

**Comment by danereinsch** [comment]
> Entire TR tree? All you literally need is the TR Compressor & Generator?

A bit of an exaggeration, but it makes sense imo to add the gold ingot recipes to the Modern Industrialization forge hammer, as other basic tech reborn inefficient recipes are already added, and would make it possible to nearly only use the IR machines as your base.

**Comment by AK9Official** [comment]
Hmm, I guess I could add Gold plates.. Reason this progression is in place is because ppl will just rush the most OP tech mod and not touch anything else.

**Comment by Technici4n** [comment]
Modern Industrialization dev here. The Forge Hammer is there to allow crafting the basic machines. By design, gold plates are not needed for early game machines, and must be created using a Compressor/Presser.
