### ISSUE TITLE
Tin ingots turn into the wrong type of tin nuggets

### ISSUE THREAD

**Issue by Dathide** [TeamAOF/All-of-Fabric-3#170]
On the latest version (2.3.2), when placing a single tin ingot into the crafting grid, the output is 9 tin nuggets from "Industrial Revolution" rather than "Tech Reborn". This other type of nugget can't be turned into "Tiny Tin Dust" in the Forge Hammer, so some recipes are impossible to make. 
I place the Tech Reborn tin ingot into a crafting grid:
![crafting test 1](https://user-images.githubusercontent.com/47128084/98412230-d17dc180-2034-11eb-830d-fea2a8bd5929.png)
The output is the wrong kind of nugget:
![crafting test 2](https://user-images.githubusercontent.com/47128084/98412235-d3478500-2034-11eb-9363-f5bfc04be4f2.png)
The REI recipe looks correct, but doesn't work:
![REI recipe](https://user-images.githubusercontent.com/47128084/98412218-cb87e080-2034-11eb-9920-e021405fdfbc.png)

**Comment by AK9Official** [comment]
Fixed in 2.3.4, thanks for reporting!
