### ISSUE TITLE
Salt problem

### ISSUE THREAD

**Issue by miblachit** [TeamAOF/All-of-Fabric-3#171]
When i make salt from salt rock, it crafting to the salt from croptopia, and with this salt you cant pickle cucumbers. Thats it.

**Comment by AK9Official** [comment]
How does one even pickle the cucumber?

**Comment by miblachit** [comment]
> How does one even pickle the cucumber?

By brafting jar, then filling it with water, then placing cucumbers from sandwichable, and then placing a salt. But salt isnt craftable.
