### ISSUE TITLE
Suddenly banned from the AOF Discord and the AoF3 US server, no other way to communicate

### ISSUE THREAD

**Issue by DerpityDoo** [TeamAOF/All-of-Fabric-3#174]
As the title says, I was banned from the discord and the server suddenly last night and I don't have any other line of communication to the AoF team to request an unban.
I only played for like an hour since the wipe and now it says I'm "Banned for Griefing" and I have no idea why

**Comment by dandin87** [comment]
You broke part of the spawn tree. How would anyone thing breaking things at spawn would be ok?

**Comment by DerpityDoo** [comment]
What? no i didnt theres no way I broke the spawn tree

**Comment by DerpityDoo** [comment]
can I see a picture? or proof? I know I didn't break the tree.

**Comment by DerpityDoo** [comment]
Any news? I feel like someone should care about people getting randomly banned from both server and discord for things they didn't do

**Comment by DerpityDoo** [comment]
Why am I still banned?

**Comment by ImAK9** [comment]
Who even are you

**Comment by DerpityDoo** [comment]
Derpity_Doo, i played for a couple weeks on the US server, then I played for like 2 hours after the wipe and came back and was banned

**Comment by DerpityDoo** [comment]
Trent says i broke the tree, but I think that's bullshit and I did no such thing

**Comment by dandin87** [comment]
I am only relaying the message. Monster Zero banned you after seeing the a block log and mahogany in your inventory. Gryz is forgiving about his tree and you may not have done all of it, maybe you accidently mined a block. Idk. Be very grateful as normally complaining over and over would just make us continue to ignore it. A few of us realize you never did anything before and so feel like you deserve another chance. Good Luck.
