### ISSUE TITLE
I cant craft wrench from Tech Reborn, because

### ISSUE THREAD

**Issue by miblachit** [TeamAOF/All-of-Fabric-3#177]
When i crafting bronze ingot, it crafts into ingot from modern industrialization. And with this ingots, i cant craft wrench. 
None other than that work.

**Comment by yorii** [comment]
how did you craft the bronze ingots?

**Comment by miblachit** [comment]
just by placing bronze bar in crafting table.

> how did you craft the bronze ingots?

**Comment by yorii** [comment]
> just by placing bronze bar in crafting table.
> 
> > how did you craft the bronze ingots?

There is no item called a bronze bar

**Comment by Technici4n** [comment]
Fixed in newer versions
