### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Avashel** [TeamAOF/All-of-Fabric-3#178]
I made a single player world and had a LAN server with my husband. The next time we went to play on it it seemed the world had corrupted as I would get crash report every time I tried to open it. Thought it might be due to the recent update so we made a new world as we only had a few hours in it. We had 2 sessions and when I went to open the game to play today it was doing the same thing. Unable to submit a crash report on the twitch modpack page. 
his is frustrating as I can't enjoy playing the mod with my hubby. It was looking to be a new fav as we like the mods and the biomes.

Help to fix this would be great as we put a lot of hours in on our last session and really liked our building area and building we had constructed. Starting over a new session is super annoying and we also do not want to go on the hunt again for a new modpack to play

. Thank you for any help you can provide. I have attached the crash report and a screenshot of the general error. 

![MC crash error](https://user-images.githubusercontent.com/74209825/98588515-0da96000-2289-11eb-98c9-e21302dc735e.JPG)

[crash-2020-11-09_12.40.50-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5512889/crash-2020-11-09_12.40.50-server.txt)

**Comment by Technici4n** [comment]
This is an HQM crash, it should be fixed in later versions where HQM was removed.
