### ISSUE TITLE
Nickel not spawning underground

### ISSUE THREAD

**Issue by xDeezer** [TeamAOF/All-of-Fabric-3#179]
There could also be other ores that are not spawning in caves, but I'm still at the beginning of understanding the tech and stuff so i'm not really sure what else could be missing.

**Comment by Yoosk** [comment]
Nickel is not supposed to generate in world, you can obtain it by other means.

**Comment by xDeezer** [comment]
Thanks, this crafting method is not specified on the usual recipes, Have a nice day!
