### ISSUE TITLE
startserver forcedjavapath

### ISSUE THREAD

**Issue by Quezler** [TeamAOF/All-of-Fabric-3#182]
line `12` of `startserver.sh` does not use the forced java path from `server-setup-config.yaml`
(causing it to fail in my case, requiring a manual edit)

**Comment by Yoosk** [comment]
Yes, because forced java path should be only for your launched server, not for serverstarter.

**Comment by Quezler** [comment]
ah, well at the time i downloaded the server release it did not work for java 14
