### ISSUE TITLE
Pumpking carving crash + crafting recipe

### ISSUE THREAD

**Issue by listerla** [TeamAOF/All-of-Fabric-3#188]
The carving knife is uncraftable as you instead craft a pipe probe. However, this is good, because if you carve a pumpkin using the knife, the rendering of the block will cause instant crashes.

**Comment by CoolMineman** [comment]
If Ignis Fatuus has a crash issue please make a bug report with your log on the issue tracker [https://github.com/CoolMineman/ignis-fatuus/issues](https://github.com/CoolMineman/ignis-fatuus/issues)
