### ISSUE TITLE
Vein mining with a base Modular Mining Drill acts like a hammer

### ISSUE THREAD

**Issue by Dathide** [TeamAOF/All-of-Fabric-3#189]
When holding the ~ key and mining with a Modular Mining Drill (MMD) that has no upgrades, only the blocks in a certain direction are mined. The other drills (MK1-MK3) have the expected vein mining behavior. I suspect that the MMD may have been given the same vein mining properties as hammers because it can be upgraded to mine 3x3-11x11 areas. This is useful when using the MMD and ~ key is used in hammer mode, but the issue arises when this is turned off or these upgrades aren't applied. Without upgrades, the MMD can only mine one block at a time like a pickaxe. It is impossible to vein mine blocks like coal ore when mining with an MMD, meaning that regular pickaxes and the lower grade drills are more useful in regular mining circumstances. Ideally, the MMD would use hammer Diggus mode when the Range Modules are turned on, and use the regular Diggus mode when the Range Modules are turned off or not applied.
![2020-11-13_15 09 20](https://user-images.githubusercontent.com/47128084/99125916-5b440680-25c2-11eb-97ef-462026531954.png)

**Comment by GabrielOlvH** [comment]
Sounds like Magna and Diggus Maximus don't play along very well. I'm not sure if this is fixable but I'll look into it. Also if you could move this issue to https://github.com/GabrielOlvH/Industrial-Revolution would be better, this doesn't have anything to do with the pack.

**Comment by Dathide** [comment]
Thanks, I'll copy this issue over and then close it.
