### ISSUE TITLE
Using Electric Smelter From Astromine crashes the game

### ISSUE THREAD

**Issue by Kazenagi89** [TeamAOF/All-of-Fabric-3#19]
HI i play latest version of AoF3 from twitch app and whenever i try to use electric smelter from astromine it crashes.

**Comment by BlueskyClouds** [comment]
me too

**Comment by Boundarybreaker** [comment]
Can either of you provide a crash log, please?

**Comment by BlueskyClouds** [comment]
[minecraft-exported-logs-2020-07-18T18-27-09.log](https://github.com/TeamAOF/All-of-Fabric-3/files/4941472/minecraft-exported-logs-2020-07-18T18-27-09.log)

**Comment by Boundarybreaker** [comment]
Logged as [Astromine#157](https://github.com/Chainmail-Studios/Astromine/issues/157)

**Comment by BlueskyClouds** [comment]
@Boundarybreaker  I tried to download the latest version (astromine-1.2.1+fabric-1.16.1) from the official website and manually replace the old version and found that the problem has been fixed.

**Comment by vini2003** [comment]
I advise updating Spinnery to version 3.0.56 and Astromine to 1.2.1 as the issue is not reproducible on our end.
