### ISSUE TITLE
Dank 1 recipe requires barrels that are impossible to craft

### ISSUE THREAD

**Issue by Dathide** [TeamAOF/All-of-Fabric-3#190]
When attempting to craft a barrel to make a Dank 1, barrels from "Charm" are made instead of those from "Blockus". The Blockus barrels are the only ones that work in the recipe.

**Comment by ImAK9** [comment]
Disable barrels in the config for now

**Comment by ImAK9** [comment]
Thing is it’s disabled but not reading config for some reason.. https://github.com/TeamAOF/All-of-Fabric-3/blob/master/config/charm.json

**Comment by Technici4n** [comment]
Should be fixed in 2.4.2
