### ISSUE TITLE
Every mountable entity has the camera locked to one position making minecarts, boats horses etc. unusable

### ISSUE THREAD

**Issue by justabread** [TeamAOF/All-of-Fabric-3#191]

**Comment by yorii** [comment]
I can't really reproduce this, on what version are you having the problem?

**Comment by Kami-Coding** [comment]
Im having the same problem with litterly the first minecart placed after reading this

**Comment by dandin87** [comment]
Remove the mod Linkart. It is removed in the next update. I believe when Mojang added pitch and yaw to player position this mod broke.
