### ISSUE TITLE
Everything worked fine yesterday, but this morning, after the update, I cannot log into my server anymore. Single player works fine.

### ISSUE THREAD

**Issue by kianbfan** [TeamAOF/All-of-Fabric-3#193]
I have the server hosted via Aternos. I even tried completely resetting and reinstalling the server, but the error is the same.

On the client side I get an error stating that I received an incomplete set of tags from the server.

I have attached the log below on from the server.

https://mclo.gs/neNOL8i

Edit: I tried downloading the server pack and hosted it myself to see if the problem was Aternos. Same problem.

**Comment by yorii** [comment]
that error is usually due to client/server mismatch, are you sure both the server and client are on the same version?
