### ISSUE TITLE
Incomplete set of tags received from server.

### ISSUE THREAD

**Issue by Wazard** [TeamAOF/All-of-Fabric-3#198]
I've just installed the server and the modpack. Singleplayer works fine and the server I am hosting doesn't give errors even though i can't enter the server cause of this error
[latest.log](https://github.com/TeamAOF/All-of-Fabric-3/files/5560190/latest.log)

**Comment by Technici4n** [comment]
Please check that the client and the server have the same version of the modpack!

**Comment by Wazard** [comment]
Same version. Server downloaded from twitch an installed with the .bat
Modpack download from twitch and installed via MultiMC

**Comment by Yoosk** [comment]
Log you provided does not look like from fabric server or aof3 server, and offline mode?

**Comment by Wazard** [comment]
I downloaded the server then hosted via Hamachi, offline mode 'cause some friend of mine are not using the legit Minecraft

**Comment by Yoosk** [comment]
You can not play fabric without legit account. And seems your server is not installed properly.

**Comment by Wazard** [comment]
Ok, I'll try installing it again. Thanks

**Comment by Technici4n** [comment]
You can try downloading the server directly from CurseForge: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3114122

**Comment by Wazard** [comment]
This is the one i am using. Doing all again and let you know

**Comment by Wazard** [comment]
it works now, the problem was java's path being cursed

**Comment by Technici4n** [comment]
ok, good!
