### ISSUE TITLE
Biome type change after update

### ISSUE THREAD

**Issue by Wtoll1** [TeamAOF/All-of-Fabric-3#20]
I got an issue on the Cinderscapes page from a user of AOF-3 saying that they recently updated the pack and had a previously normal overworld biome turn into a Cinderscapes nether biome. I’m guessing that another biome mod was added or added a new biome and that it messed with the registry (apparently fabric is supposed to have a fix for this but I don’t know enough about that). Either way I might just add a message on the update saying that updating might cause unintended changes to biomes. I don’t know enough about which versions this affects the user only said recently, I’ll try to find out more though.

**Comment by davidthehat** [comment]
I'm having this issue as well. The issue occurs when updating from 1.3.1 to any 1.4 version. The one difference is 1.4.0, where the bug still occurs but the biome is changed to a different one than the other 1.4 versions.

If I create a new world with the same seed as my old world, the world generates correctly, with the correct biomes. Likewise, if I generate new chunks in a bugged world, the new chunks are generated with the correct biome.

Although the Cinderscapes biomes in the overworld issue is probably the biggest, as it allows for the spawning of nether mobs in the overworld, the seemingly random biome changes have other annoying effects, like my beach freezing over and improper foliage coloring.
