### ISSUE TITLE
Can't join my MultiCraft server

### ISSUE THREAD

**Issue by ObeyGrave** [TeamAOF/All-of-Fabric-3#202]
using the Twitch launcher btw

HELP!
![Desktop Screenshot 2020 11 20 - 03 16 58 50](https://user-images.githubusercontent.com/74763137/99776469-e0597f00-2ade-11eb-9098-91a704e32f1c.png)

**Comment by dandin87** [comment]
You are gonna need to give more info than that. What version of the pack is the server running? What version are YOU running. All i see is AoF3 1.16.4. Btw that is the curseforge/overwolf launcher, no longer a part of twitch.

**Comment by ObeyGrave** [comment]
All of Fabric 3 - 1.16.4 is what the sever is running and I'm choosing All of Fabric 3 - 1.16.4 in the launcher ( just tired in the twitch launcher and no luck)

**Comment by kabadesu** [comment]
Can you check that the version you're running matches the one you're trying to connect to?

NA server is running 2.4.3
EU server is running 2.4.4

**Comment by Technici4n** [comment]
Looks like someone added blocks with KubeJS on the server side, and you don't have them on the client side...

**Comment by ObeyGrave** [comment]
![image](https://user-images.githubusercontent.com/74763137/99780491-8eb3f300-2ae4-11eb-8a6f-224f7ccd23e1.png)
everytime i change the version it just reverts it back to 2.4.4. not entirely sure why.

**Comment by Technici4n** [comment]
Did you add blocks with KubeJS ?

**Comment by ObeyGrave** [comment]
no, i havent

**Comment by Technici4n** [comment]
What the hell is `kubejs:nether_star_block`...

**Comment by ObeyGrave** [comment]
I HAVE NO IDEA! i just clicked in my multicraft " All of Fabric 3 - 1.16.4" and opened my twitch launcher AND forge launcher and pressed play after downloading the mods, even changed versions , and nothing. keep getting the same error. i didnt touch anything in the files
