### ISSUE TITLE
Coke Oven & Steam Blast Furnace, no interface

### ISSUE THREAD

**Issue by HenriU-ZA** [TeamAOF/All-of-Fabric-3#204]
![2020-11-21_20 29 23](https://user-images.githubusercontent.com/63014339/99884613-545b6a80-2c38-11eb-836d-0c24977b8295.png)
![2020-11-21_20 29 28](https://user-images.githubusercontent.com/63014339/99884616-58878800-2c38-11eb-9b10-1134b63af28f.png)
The coke oven and the Blast furnace has no interface.

**Comment by Technici4n** [comment]
MI dev here... That's intended, you are supposed to use hatches to interact with the coke oven! I suggest you read the coke oven entry of the guide book... ;-)
