### ISSUE TITLE
Intermittent Crashes when searching with REI

### ISSUE THREAD

**Issue by KangyKSLG** [TeamAOF/All-of-Fabric-3#208]
Hi, sometimes when searching for items in REI my game just suddenly closes and goes back to the launcher. This is the screen I see
![image](https://user-images.githubusercontent.com/42292756/100026595-020a7d00-2de3-11eb-8216-6136063bba73.png)

The game doesn't create a crash log or show anything in the logs but i've attached them anyway
[latest.log](https://github.com/TeamAOF/All-of-Fabric-3/files/5586358/latest.log)

**Comment by Technici4n** [comment]
Hi, you need to disable "Fast Entry Rendering" in REI's settings when using canvas!

**Comment by KangyKSLG** [comment]
Thanks, that seems to have worked. I'll close the issue :)
