### ISSUE TITLE
Nether portal link

### ISSUE THREAD

**Issue by Ectalite** [TeamAOF/All-of-Fabric-3#21]
Hello, I‘m playing on a self hosted server with friends and everytime we create another portal in the nether it is always linked with the first one we created at the spawn. When go through a portal from the overworld it does work fine but not from nether to overworld. 

Thanks for creating such good modpacks !
PS: could you add sodium in the next modpack update as it improves the game experience ?

**Comment by dandin87** [comment]
https://www.curseforge.com/minecraft/mc-mods/pethernortalflux this mod should help your netherly needs. Portals have to be made 1024 blocks apart in the overworld and 1024/8 in the nether without this mod, as that is vanilla Minecraft behavior. This mod should fix that, I have not tested it though.

Sodium currently does not support the Fabric Rendering API and so some of the items in the modpack will appear invisible. Specifically Companion mod Rope Bridges, and all the items from Packages mod, I also think Tech Reborn Batteries. Sodium 0.2 should be fixing this but that has no ETA and so cannot be included for that reason. It is however still very usable in the pack if you don't mind those things being invisible.

**Comment by Ectalite** [comment]
Thanks for very quick response, yeah I saw that one item wasn‘t rendered properly. I will test pethernortalflux. 

25 juil. 2020 à 09:50 de notifications@github.com:

**Comment by Ectalite** [comment]
It worked very good.
