### ISSUE TITLE
When i die i dont get a death chest

### ISSUE THREAD

**Issue by Wiggleboi789** [TeamAOF/All-of-Fabric-3#214]
So when ever i die usually i read a chest will spawn in and give you your stuff. but when i died Nothinf spawned in

**Comment by yorii** [comment]
Check around the local area, it will sometimes spawn underwater or up in a tree.

**Comment by yorii** [comment]
Also if it's lagging, the death chest can spawn in very weird locations, it has been reported to spawn at:
A) close to your respawn location after death
B) at the same coords of your respawn location, but in the dimension where you died
