### ISSUE TITLE
Game crash: Exception ticking world

### ISSUE THREAD

**Issue by AndreVallestero** [TeamAOF/All-of-Fabric-3#215]
```
	at net.minecraft.class_2985.method_12885(class_2985.java:344)
	at net.minecraft.class_2985.method_12885(class_2985.java:348)
```

Full log file:
[crash-2020-11-24_06.40.49-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5590917/crash-2020-11-24_06.40.49-server.txt)

RER has already been removed from the server prior to this crash.

**Comment by ImAK9** [comment]
fixed in newer versions.

**Comment by CatusKing** [comment]
i have the same problem

**Comment by CatusKing** [comment]
[crash-2020-11-24_06.40.49-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/8180955/crash-2020-11-24_06.40.49-server.txt)
