### ISSUE TITLE
Game crash: Exception ticking world

### ISSUE THREAD

**Issue by AndreVallestero** [TeamAOF/All-of-Fabric-3#216]
This is different from https://github.com/TeamAOF/All-of-Fabric-3/issues/215

Full log file:
[crash-2020-11-22_23.04.26-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5590925/crash-2020-11-22_23.04.26-server.txt)

RER has already been removed from the server prior to this crash.

**Comment by dandin87** [comment]
No it has not been removed. 
	at uk.me.desert_island.rer.WorldGenState.toNetwork(WorldGenState.java:144)
https://github.com/theorbtwo/RoughlyEnoughResources/blob/1.16/src/main/java/uk/me/desert_island/rer/WorldGenState.java

**Comment by AndreVallestero** [comment]
> 
> 
> No it has not been removed.
> at uk.me.desert_island.rer.WorldGenState.toNetwork(WorldGenState.java:144)
> https://github.com/theorbtwo/RoughlyEnoughResources/blob/1.16/src/main/java/uk/me/desert_island/rer/WorldGenState.java

I'm new to modded. I thought removing RER from my server's mod list would be sufficient. Is it not?

**Comment by Technici4n** [comment]
You need to remove RER from `server-setup-config.yaml`.
