### ISSUE TITLE
Game crash when using BLAST's stripminer

### ISSUE THREAD

**Issue by ironsnake345** [TeamAOF/All-of-Fabric-3#224]
Paste of crash log: https://pastebin.com/9V70RAHF

Let's be a bit more specific, then. BLAST adds a "stripminer" explosive which is supposed to create a 3X3 tunnel for a ways down the wall it's placed against, and I was hoping to use it for my own mining purposes. But, whenever I place down the stripminer and try to ignite it with flint and steel, it just vanishes, becoming sort of a "phantom block." I can't walk into the empty space left, because the game keeps pushing me back out of it, and whenever I try to interact with something through that "phantom block," the stripminer suddenly reappears, having apparently not been primed at all. Using redstone doesn't work either; the redstone device that would trigger the stripminer just kind of freezes in the "active" state. I've only tested it with a button, but whether I placed the button directly on the stripminer or on the block adjacent, it gets stuck in the "pressed" state.

Then, we come to the crash. I tried to trigger the stripminer using a bomb from the same mod, since explosions trigger explosives. But, the moment the bomb explodes, my game crashes, generating the crash log above. Then, when I go back into the world, the stripminer is back in my inventory instead of in the world (as well as the bomb I used to trigger it), the button I tried to use to trigger the stripminer has become a drop, and there is no blast hole. I've repeated this process 3 times, it happens the exact same way every time.

I don't know if this is an issue with this modpack, or with BLAST specifically, or what; if I'm barking up the wrong tree, let me know.

**Comment by dandin87** [comment]
Don't use the word crash if it is not crashing...... This is a known issue and has been reported, and is being worked on by the dev. https://github.com/Ladysnake/BLAST/issues/8

**Comment by ironsnake345** [comment]
It is crashing, though. This explicitly causes a game crash when I trigger the stripminer using explosives, as stated in the third paragraph. The second paragraph is just for context, and extra information that might be helpful.

**Comment by dandin87** [comment]
Ah apologies, I should have read the whole thing. Well the dev is working on a fix, thanks for letting us know it can also cause a crash.

**Comment by TrueCP6** [comment]
This issue was fixed in the latest version of Blast.
