### ISSUE TITLE
Astromine tech seems poorly supported in the pack

### ISSUE THREAD

**Issue by stefment** [TeamAOF/All-of-Fabric-3#225]
Hi, i was gonna try out astromine in my 2.5.0 world but it seems the Trituator cannot create all the dusts that the indrev or tech reborn grinder/pulverizer can. And the Astromine presser cannot create all the plates and stuff that the indrev compressor and tech reborn compressor can. Is this intentional? And if so.. Why? 

Kind regards
STEFFEN

**Comment by IMS212** [comment]
Astromine was just announced to be discontinued.

**Comment by stefment** [comment]
ouch
