### ISSUE TITLE
Anyone has a wild explorer problem?

### ISSUE THREAD

**Issue by Mar0o** [TeamAOF/All-of-Fabric-3#226]
wild_explorer:amaranth_roots
-wild_explorer:amaranth_dylium
-wild_explorer:amaranth_wart_block
 this is a thing that shows when i try to log into my server for some reason this msg always pops up any idea what to do?

**Comment by kabadesu** [comment]
Is the server and client running the same version?

**Comment by Mar0o** [comment]
ive just realiye dthere was a client update mz bad
