### ISSUE TITLE
AE2 Autocrafter Crash

### ISSUE THREAD

**Issue by Labyrinthia** [TeamAOF/All-of-Fabric-3#230]
Trying to send a request to the autocrafter via the ME Crafting Terminal resulted in a crash.

[crash-2020-12-09_21.54.05-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5673832/crash-2020-12-09_21.54.05-client.txt)

**Comment by bulldog98** [comment]
There is a bug report for AE2: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4765
Seems like Inventory Sorter is responsible for the crash

**Comment by Monster-Zer0** [comment]
this was reported to mod author. so this issue has been handed off.
