### ISSUE TITLE
Server crash caused by mod Phonos!

### ISSUE THREAD

**Issue by ZYLHL** [TeamAOF/All-of-Fabric-3#234]
When I put a record in a phonos' CD Machine , The server crashed.
the crash-reports are belows:
[crash-2020-12-14_02.45.59-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5685228/crash-2020-12-14_02.45.59-server.txt)
[crash-2020-12-14_02.47.27-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5685229/crash-2020-12-14_02.47.27-server.txt)
[crash-2020-12-14_02.39.41-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5685230/crash-2020-12-14_02.39.41-server.txt)
[crash-2020-12-14_02.41.00-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5685231/crash-2020-12-14_02.41.00-server.txt)
[crash-2020-12-14_02.43.07-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5685232/crash-2020-12-14_02.43.07-server.txt)

**Comment by ZYLHL** [comment]
modpack edition is 2.5.2

**Comment by loginlogout3** [comment]
I have had similar server crashes on both versions 2.4.3 and 2.5.4. Mine happens when I hit the play button in the Phonos cd machine.

**Comment by MissPotato** [comment]
Phonos devs know about it but they're not really sure what's causing it as it doesn't happen in their test server.
