### ISSUE TITLE
FPS drops and client disconnects in single player when looking at large/complex inventories

### ISSUE THREAD

**Issue by velotican** [TeamAOF/All-of-Fabric-3#236]
This issue can be reproduced by placing any Obsidian Barrel/Chest or Netherite Barrel/Chest (from ExtendedStorage) in AOF 2.5.4 and above. You should disconnect as soon as the chest is placed. The NBT tag size limit is apparently being exceeded when Hwyla attempts to scan the inventory's contents. A Diamond Barrel/Chest with sufficiently complex items placed in it will also trigger the disconnect. Gold Barrels and Chests appear to be OK.

Temporarily pulling Hwyla and all addons from the pack solves the issue. Prior to recent versions of the pack, the NBT limit error was being recorded in the logs but was not triggering a disconnect.

While attempting to troubleshoot this issue and recover my base inventory, I noticed that disabling the inventory scan in Hwyla's megane plugin fixed the strange FPS drops I'd been having over the last few weeks in certain spots of my factory floor. It looks like this function is triggering whenever you look at any block whether you care about the inventory contents or not.

**Comment by Monster-Zer0** [comment]
still issue?

**Comment by velotican** [comment]
My apologies, I'm currently playing other games and haven't updated the modpack in some time. I'll fire up a test instance of 2.6.7 in the next few days and get back to you.

Were you unable to reproduce the issue on your end in 2.5.4, out of curiosity?

**Comment by Monster-Zer0** [comment]
thank you for the follow up. it is highly appreciated.
