### ISSUE TITLE
Quitting to main menu in a single player world and loading any world afterwards not working correctly

### ISSUE THREAD

**Issue by velotican** [TeamAOF/All-of-Fabric-3#237]
This has been an issue since AOF 2.2.0 but appears to have become worse in the latest update.

While everything works normally when starting fresh and loading the first world to play, exiting to the menu and trying to load another world (or the same world) does not work correctly.

Prior to 2.5.4, the world would load, but be unresponsive - no chunks other than the ones around you would load, and all objects such as buttons, levers and furnaces would ignore player inputs. Special armour functions and enchantments would also do nothing. Attempting to quit the world in this state would do nothing and the process has to be terminated manually each time. Fortunately this does not corrupt save files.

Restarting AOF3 fixes the problem until you exit to main menu from a running single player world again. As of 2.5.4, worlds subsequent to the first loaded do not always successfully finish loading, but remain unresponsive if they do load. In either case, the client process has to be manually terminated.

**Comment by Monster-Zer0** [comment]
how much ram do you have allocated?

**Comment by velotican** [comment]
After looking up the settings I was using at the time, it seems I allocated 4GB to the modpack (+128MB permgen if that matters). I think those are/were the recommended settings?

**Comment by velotican** [comment]
This issue appears to persist in 2.6.7.

An addendum: creating a new world, exiting it and loading an existing save does not fully trigger the fault, although the second world is unresponsive for a few seconds after loading in.

It was reloading that world after exiting that triggered the same hanging issue I reported before.

**Comment by ImAK9** [comment]
Fixed in latest builds.
