### ISSUE TITLE
Not all mods installed?

### ISSUE THREAD

**Issue by ahplasmind** [TeamAOF/All-of-Fabric-3#238]
One of the mods that I found interesting was the Industrial Revolution mod that is listed on the curseforge page. I started a world and played around for a bit, but I looked through the Roughly Enough Items mod and did not find any of the tech from Industrial Revolution.

Is the mod, Industrial Revolution, ACTUALLY in the modpack or not? If it is, is there away to fix my issue? Thanks in advance!

**Comment by Monster-Zer0** [comment]
please try a newer version of the pack
