### ISSUE TITLE
Quartz Dust not fully unified 

### ISSUE THREAD

**Issue by MissPotato** [TeamAOF/All-of-Fabric-3#239]
Cinderscapes quartz can be grinded into quartz powder in the Triturating machine, and they can be used as nether quartz in most erafting recipes. However the follow mods and their machines can not make quartz dust out of cinderscape: Inudstrial Revolution's Pulverizer, Tech Reborn's Grinder, Modern Industrialization's Macerator.

**Comment by ImAK9** [comment]
I’ll look into that tomorrow
