### ISSUE TITLE
Randomly can't mine blocks, pick up blocks, and sleeping in bed doesn't switch time to day.

### ISSUE THREAD

**Issue by lolsevryday** [TeamAOF/All-of-Fabric-3#24]
Sometimes when I am playing All of Fabric 3, when I mine a block, it just replaces it self, and I don't get the block. I can mine grass though, but when it drops seeds or other items, it won't let me pick up the items. Also, when I sleep in a bed, the time doesn't change to day. The only fix I know is to restart the game.

**Comment by dandin87** [comment]
This sounds like the server is lagging (even single player the world is still a server). Did you make sure your Minecraft launcher is set to give it 4G of RAM, or more? You can add the Java Arg -Xmx4G or increase it with the launcher's settings.

**Comment by lolsevryday** [comment]
> 
> 
> This sounds like the server is lagging (even single player the world is still a server). Did you make sure your Minecraft launcher is set to give it 4G of RAM, or more? You can add the Java Arg -Xmx4G or increase it with the launcher's settings.

Yeah, I have gave it 4G for my singleplayer world. I'll try allocating more then

**Comment by AK9Official** [comment]
@lolsevryday Is this solved? If not feel free to repopen.
