### ISSUE TITLE
CurseForge 2.5.4 server pack missing mod and server files

### ISSUE THREAD

**Issue by nanakisan** [TeamAOF/All-of-Fabric-3#241]
Per the title the curseforge page's provided server distribution is lacking mods, configs and the server files. I could use the main distribution for this purpose. But I would be spending so much time figuring out what is client side only and what isn't client side. The server zip should be already built and able to be extracted without issue.

**Comment by nanakisan** [comment]
Ok so I figured out what you lot did. I am not ok with this method of server distribution. CurseForge gives you the power to make a separate file people can download the server files. Why offer that file but also offer a .bat that then downloads the files for us? This is counter intuitive to CurseForge's intended use for the platform. Please reconsider this and just use the zip file distribution method as intended. That or at least mention this in the mod pack description.

**Comment by dandin87** [comment]
We use the curseforge api to download the mods. That is perfectly inline with curseforge. If it was not they would not approve it. Hosting sites also have no trouble offering the curseforge server pack.

**Comment by Yoosk** [comment]
We are using `zip file distribution method` as intended. Serverstarter is perfect for any kind of server as you are not forced to dump 200mb modpack over ftp if you have remote server, and even locally its downloading only server-side mods that are needed.

**Comment by nanakisan** [comment]
I just want to apologize for what I said. Looking over it I was definitely in the wrong. So I am just retracting everything I said. Sorry about that!
