### ISSUE TITLE
The design philosphy of the modpack is genius

### ISSUE THREAD

**Issue by stefment** [TeamAOF/All-of-Fabric-3#242]
The way you disable machines and recipes to force people to go a specific route for tech is really interesting. Very enjoyable. Its especially interesting for people who are doing a second playthrough and have to build the excact same machines again

**Comment by ImAK9** [comment]
Not a single machine is disabled. You craft the TR compressor and you can do whatever the F you want.

**Comment by stefment** [comment]
That is a stroke of genius. Having to craft the TR compressor before being able to do anything is awesome. It adds alot to the experience. I dont know how you come up with these things. Btw. is the AE2 grinder still disabled?

**Comment by ImAK9** [comment]
AE2 grinder has 0 use and cant be unified.

**Comment by stefment** [comment]
If it has 0 use then why disable it?

**Comment by ImAK9** [comment]
Beauty of choice is that you can pick whichever pack of your choice to play :)

**Comment by ImAK9** [comment]
> If it has 0 use then why disable it?

Because players crafted it and couldnt use it, obviously.

**Comment by stefment** [comment]
So choice is fine when it comes to modpacks but not when it comes to options within the modpack

**Comment by ImAK9** [comment]
What are you on about, literally make the Compressor then make whatever the fuck machine you want. The compressor is literally the first machine you would have to make either way. That’s how TR is designed.

**Comment by stefment** [comment]
Im not sure how i can explain this to you, you seem denser than i thought

**Comment by ImAK9** [comment]
Boohoo

**Comment by dandin87** [comment]
You are free to change whatever you want feor your server or single player. /kubejs/server_scripts you are being dumb af stefment

**Comment by stefment** [comment]
First we are forced to make MI hammer to get started with tech. Then we have to stat with TR specifically. Then we can make other tech mods if we want. Its bloated af

**Comment by ImAK9** [comment]
Hahaha what, that’s literally how the devs designed their mods idiot.

**Comment by stefment** [comment]
Oh so its not bloated then. Gotcha

**Comment by ImAK9** [comment]
I’m sorry but you’re next level low IQ.

**Comment by stefment** [comment]
You wish

**Comment by ImAK9** [comment]
”You wish”, are you like 14?

**Comment by stefment** [comment]
Why have you resorted to name calling and insults?

**Comment by ImAK9** [comment]
> Why have you resorted to name calling and insults?

You’re obv upset about it, hence those ”insults” somehow must be true?

**Comment by stefment** [comment]
You are the one who seems upset tbh

**Comment by stefment** [comment]
Looking forward to your next stroke of genius

**Comment by ImAK9** [comment]
What can I say, I'm a sucker for drama & chaos.
