### ISSUE TITLE
Server kicks player when op-ing them

### ISSUE THREAD

**Issue by TheApolloGaming** [TeamAOF/All-of-Fabric-3#243]
Whenever i give anyone op. it will disconnect them from the server and give them this error.
Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location:
aft:ask_server advancement minecraft minecraft:resource_location minecraft:ask_server set add remove value

not sure what is causing this as the server console is not showing any errors apart from the the player disconnecting.
im using all of fabric 3 (Version 2.5.2)

![server error](https://user-images.githubusercontent.com/26276372/102613674-d0a77780-412a-11eb-8a53-6ed5bab81876.PNG)

**Comment by Monster-Zer0** [comment]
still issue?

**Comment by supsm** [comment]
I don't think so... I op-ed myself and it seems to be fine
