### ISSUE TITLE
AOF3 Sound issues

### ISSUE THREAD

**Issue by Heliocentriclump** [TeamAOF/All-of-Fabric-3#244]
Hi,  I am using AOF3 through Curse/Forge. Sound does not work. Ambient sound and music worked during one load, and did not work on the next. A screen shot of sound settings is attached (I made sure sound was on...). I have deleted and reinstalled, reloaded resources and no still no sound. Suggestions on what to try next are appreciated. This is a great pack, and I'm looking forward to playing it...
<img width="1373" alt="Screen Shot 2020-12-19 at 8 40 06 AM" src="https://user-images.githubusercontent.com/76261013/102695777-520c1200-41de-11eb-9d1a-064f5aa8cf4c.png">

**Comment by mattbradley1** [comment]
I'm having a similar issue. Only able to hear non-vanilla ambient sounds. I'm playing version 2.5.4 on a mac running Mac OS 11.1

**Comment by iep1000** [comment]
I'm currently having the same issue. I am only getting the ambient noises. No block sounds, player generated noises (ie. eating or falling). animal sounds or hostile mobs. Glad to hear it's not just me having this problem. I thought maybe I installed the pack wrong

Running 2.5.4 on Mac OS 10.15.7. Computer is running sound through the build in speakers.

**Comment by mattbradley1** [comment]
I have new information to add. I was experiencing this issue while loading AOF3 using CurseForge. However, when I instead loaded the modpack in MultiMC I am now able to hear sounds as normal. I'm not sure why this fixed it but hopefully this information is helpful to someone.

**Comment by dandin87** [comment]
Curseforge and even the old Twitch launcher have always had intermittent issues with downloading all the game files and/or mod files. We always recommend Using Either GD Launcher or MultiMC, as they rarely have issues

**Comment by CesarVerissimo** [comment]
Also having this issue, couldn't find any fix for it.

**Comment by Yoosk** [comment]
> 
> 
> Also having this issue, couldn't find any fix for it.

Buy the game and then we can provide support.
