### ISSUE TITLE
Can't even load

### ISSUE THREAD

**Issue by TH3GOD88** [TeamAOF/All-of-Fabric-3#245]
Every time I try to launch the game, it just crashes.

[crash-2020-12-19_13.52.32-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5720014/crash-2020-12-19_13.52.32-client.txt)

**Comment by Jensig** [comment]
I recommend that you try to install the pack with an outer launcher. GDLauncher or MultiMC is recommended!

**Comment by Yoosk** [comment]
Old java, wrong/no java arguments, no gpu or cpu visible to the game, too much RAM allocated, there seems to be plenty of issues.

**Comment by TH3GOD88** [comment]
MultiMC also crashes..... 

[crash-2020-12-19_17.03.45-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5720202/crash-2020-12-19_17.03.45-client.txt)

**Comment by TH3GOD88** [comment]
> Old java, wrong/no java arguments, no gpu or cpu visible to the game, too much RAM allocated, there seems to be plenty of issues.

What java does 1.16.4 need? No GPU or CPU visible to the game? How does fabric look for it? 8GB is too much? Not very helpful by just saying, "There seems to be plenty of issues.".

**Comment by dandin87** [comment]
-Xms512m -Xmx1024m <--- multiMC is only set for 1G ram, should be about 4G

**Comment by TH3GOD88** [comment]
> -Xms512m -Xmx1024m <--- multiMC is only set for 1G ram, should be about 4G

[crash-2020-12-19_17.14.38-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5720208/crash-2020-12-19_17.14.38-client.txt)

**Comment by dandin87** [comment]
dishes: Delicious Dishes 1.0.1 <-- this mod is not in the modpack. Its conflicting with something so you will need to remove it

**Comment by TH3GOD88** [comment]
Okay, took it out, now it is saying a mod called extraalchemy is causing the problem, yet it isn't in the folder.

[crash-2020-12-19_17.32.34-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5720230/crash-2020-12-19_17.32.34-client.txt)

**Comment by TH3GOD88** [comment]
Decided to delete the whole thing and redownload it. Now it seems to be working.

**Comment by dandin87** [comment]
Is this the curseforge launcher? many users have been having problems with it downloading everything correctly. We recommend using GD Launcher https://gdevs.io/ or MultiMC https://multimc.org/

**Comment by TH3GOD88** [comment]
Yes, it was the curse launcher. I've been trying to install GDLauncher, but it has been stuck halfway for about 2 hours. Thank you for the help.
