### ISSUE TITLE
All of Fabric 3 Fails to start

### ISSUE THREAD

**Issue by CrackedArkade** [TeamAOF/All-of-Fabric-3#246]
My log:

MultiMC version: 0.6.12-develop-1493

Minecraft folder is:
C:/Users/Arkade/AppData/Roaming/MultiMC/instances/All of Fabric 3 - 1.16.4/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_51, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/Arkade/AppData/Roaming/MultiMC/instances/All of Fabric 3 - 1.16.4/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/forge/1.16.4-35.0.17/forge-1.16.4-35.0.17-launcher.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/cpw/mods/modlauncher/8.0.6/modlauncher-8.0.6.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/eventbus/3.0.5-service/eventbus-3.0.5-service.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/jodah/typetools/0.8.1/typetools-0.8.1.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Arkade/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] [1.16.4] MoreTooltips-1.0.1
  [✔️] Adorn-1.12.2+1.16.4
  [✔️] advancements-enlarger-0.2.3
  [✔️] advdebug-2.2.0
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] appliedenergistics2-fabric-8.1.0-alpha.13
  [✔️] architectury-1.1.55-fabric
  [✔️] arstheurgia-1.0.5
  [✔️] Artifacts-2.0.2+1.16.4-fabric
  [✔️] artofalchemy-1.0.0-rc4+1.16.4
  [✔️] astromine-1.11.4+fabric-1.16.3
  [✔️] authme-1.16.3-1.4.0
  [✔️] autoconfig1u-3.3.1
  [✔️] bambootweaks-2.0.0+1.16.1
  [✔️] battletowers-3.2.1-beta-1.16.4
  [✔️] bedspreads-fabric-1.3.1-1.16.4
  [✔️] BetterCaves-fabric-1.16.2-1.0.3
  [✔️] better-enchanted-books-1.16.3-1.1.4
  [✔️] better-end-0.7.1-beta
  [✔️] BetterMineshafts-Fabric-1.16.4-1.0
  [✔️] blast-1.4
  [✔️] blockshifter-1.3.2+fabric-1.16.4
  [✔️] blockus-1.6.8+1.16.4
  [✔️] boringbackgrounds-3.0.2+1.16.3
  [✔️] byg-1.1.3
  [✔️] campanion-1.3.0+build.49
  [✔️] can-i-mine-this-block-1.0.2
  [✔️] Cardinal-Components-API-2.7.9
  [✔️] carrier-1.6.1
  [✔️] cavebiomes-0.5.1
  [✔️] cc-tweaked-fabric-1.16.2-1.91.2
  [✔️] charm-fabric-1.16.4-2.1.6
  [✔️] charmonium-fabric-1.16.4-2.1.4
  [✔️] cherishedworlds-fabric-1.3.0-1.16.4
  [✔️] cinderscapes-1.3.0+build.51
  [✔️] cleancut-mc1.16-2.1-fabric
  [✔️] cloth-api-1.4.9
  [✔️] compressedblocks-1.0.1
  [✔️] config-2-4.8.3
  [✔️] Controlling-For-Fabric-1.1.3
  [✔️] Couplings-1.3.3
  [✔️] CraftPresence-Fabric-1.16.4-Release-1.7.5
  [✔️] crookedcrooks-1.3.3+1.16.4
  [✔️] Croptopia-1.0.5-1.16.X-FABRIC
  [✔️] crusade-mod-1.2.0
  [✔️] DamageTilt-1.16-fabric-0.1.0
  [✔️] dankstorage-1.9a-1.16.3
  [✔️] DarkPaintings-fabric-1.16.3-1.0.0
  [✔️] dawn-1.6
  [✔️] decimalCoins-fabric-1.16.2-1.2.0
  [✔️] deepmoblearning-refabricated-0.3.1-beta5
  [✔️] diggusmaximus-1.4.2-1.16.3
  [✔️] DisableCustomWorldsAdvice-1.2
  [✔️] dwarfcoal-1.16.2-1.0.0
  [✔️] dynamic-fps-1.2.1
  [✔️] eggtab-1.3.2+1.16-fabric
  [✔️] expandedstorage-5.6.31+1.16.4
  [✔️] ezpas-1.2.3-1.16.2
  [✔️] fabric-1.16.1-geckolib-2.0.0
  [✔️] fabric-api-0.28.1+1.16
  [✔️] fabric-chunkpregen-0.3.3
  [✔️] fabric-furnaces-1.3.2-1.16.2
  [✔️] fabric-language-kotlin-1.4.0+build.1
  [✔️] fabric-language-scala-0.3.2.12-fat
  [✔️] fatxporbs-0.0.9+1.16.4
  [✔️] fermion-mc116-2.8.215
  [✔️] Flamingo-oh-oh-oh-1.0.4-MC1.16.3-fabric
  [✔️] Flonters-1.1.1+1.16.2
  [✔️] flora-doubling-1.3.0+1.16.4-fabric
  [✔️] GameInfo-mod-2.0.0a-experimental-06.1 1.16.2
  [✔️] gate-of-babylon-1.1.3-1.16.2
  [✔️] get-off-my-lawn-1.16.2-1.2.2-beta
  [✔️] give-me-hats-1.16-1.4
  [✔️] glassdoor-1.5.0-1.16
  [✔️] glassential-fabric-1.16.4-1.1.5
  [✔️] hard-hat-steve-1.2.0
  [✔️] Harvest-fabric-1.16.1-1.2.12-26
  [✔️] HealthOverlay-1.16.4-3.6.13
  [✔️] hwyla-addon-horseinfo-0.2.2-1.16.1
  [✔️] Hwyla-fabric-1.16.2-1.9.23-79
  [✔️] ignis-fatuus-1.1.0
  [✔️] improved-stations-2.0.3
  [✔️] indrev-1.7.15-BETA
  [✔️] inmis-2.0.0-beta-1.16.2
  [✔️] InventorySorter-1.7.4-1.16
  [✔️] iron-jetpacks-0.2.5
  [✔️] jumploader-2.1.0
  [✔️] jumpoverfences-1.16-0.0.3
  [✔️] kibe-1.16.4-1.5.2-BETA
  [✔️] lapisreserve-1.0.6
  [✔️] Library-Of-Exile-1.16.3-1.0.6
  [✔️] light-overlay-5.5.4
  [✔️] lithium-fabric-mc1.16.4-0.6.0
  [✔️] megane-3.0.7+1.16.4
  [✔️] Modern-Industrialization-0.3.9
  [✔️] modmenu-1.14.13+build.19
  [✔️] Mo-Glass-1.5-MC1.16.4
  [✔️] mostructures-1.0.1+mc.1.16.4
  [✔️] mousewheelie-1.5.10+mc1.16.4
  [✔️] netherite-plus-mod-1.1.0-1.16.4
  [✔️] no-potion-offset-1.0.2
  [✔️] notes-1.16.2-1.0.4
  [✔️] nourish-1.1.1
  [✔️] okzoomer-4.0.1+1.16.2
  [✔️] packages-1.16.4-1.1.1
  [✔️] Patchouli-1.16.4-48-FABRIC
  [✔️] phonos-0.1.0-beta
  [✔️] phosphor-fabric-mc1.16.1-0.6.0+build.7
  [✔️] pling-1.2.0
  [✔️] quickshulker-1.1.11-1.16
  [✔️] RebornCore-1.16-4.6.1+build.97
  [✔️] repurposed_structures-1.16.4-1.7.3
  [✔️] respawnablepets-1.16.4-1
  [✔️] RoughlyEnoughItems-5.8.8
  [✔️] rswires-4.9.1
  [✔️] secretrooms-0.9.2+1.16.2
  [✔️] shulkerboxtooltip-2.3.3+1.16.4
  [✔️] simpleteleporters-2.2.1
  [✔️] simplexterrain-0.7.2
  [✔️] slight-gui-modifications-1.6.1
  [✔️] slotlock-1.0.1-BETA
  [✔️] smootherbedrock-1.0.0
  [✔️] staffofbuilding-1.2.3-1.16.2
  [✔️] stonecutter-tweaks-1.1.0-1.16
  [✔️] strawdummy-1.4.0
  [✔️] survivalisland-0.1.6
  [✔️] tacocraft-1.4.0+mc.1.16.2
  [✔️] TechReborn-1.16-3.7.1+build.162
  [✔️] terrestria-2.1.5+build.28
  [✔️] TIS-3D-Additions-0.2.1+1.16.2
  [✔️] TIS-3D-MC1.16.2-Fabric-1.6.0.20
  [✔️] trapexpansion-1.16.2-1.3.3
  [✔️] traverse-3.0.3+build.13
  [✔️] trinkets-2.6.7
  [✔️] true-secret-rooms-1.0.3
  [✔️] vanilladeathchest-1.16.3-1.11.0.7-fabric
  [✔️] vanillaexcavators-2.1.2-1.16.2
  [✔️] vanilla-hammers-3.0.1-1.16.3
  [✔️] villager-hats-fabric-1.16.4-1.0.1
  [✔️] wild_explorer-1.3
  [✔️] winged-1.16.2-1.4.1
  [✔️] Wither-Totems-Mod-0.3.2-1.16.2
  [✔️] wolves-with-armor-1.5.2-1.16.2
  [✔️] woodenhoppers-1.0.0
  [✔️] WoodsAndMires-1.0.4+1.16.3
  [✔️] wraith-harvestscythes-1.0.4
  [✔️] wraith-waystones-1.0.10
  [✔️] Xaeros_Minimap_20.28.1_Fabric_1.16.4
  [✔️] XaerosWorldMap_1.11.3_Fabric_1.16.4
  [✔️] yosbr-0.1.1
  [✔️] YungsApi-1.16.4-Fabric-1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Arkade/AppData/Roaming/MultiMC/instances/All of Fabric 3 - 1.16.4/minecraft --assetsDir C:/Users/Arkade/AppData/Roaming/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 35.0.17 --fml.mcVersion 1.16.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20201102.104115

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 88104

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Can't detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:109)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:120)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:23)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 21 Dec 2020 22:10:41 +0545

**Comment by Monster-Zer0** [comment]
try a newer version
