### ISSUE TITLE
Why is the map so small and limited?

### ISSUE THREAD

**Issue by Gladox114** [TeamAOF/All-of-Fabric-3#247]
So when going to the border of the map on "M" no new chunks get added and when entering the chunks that aren't displayed on the map then nothing really happens. The chunks load way slower and when we destroy blocks there we can't pick them up.

This is on a singleplayer world shared with LAN

**Comment by nuggies-cool** [comment]
you have to explore the chunks for it to show on the map

**Comment by Gladox114** [comment]
I was standing in the new chunk while the map displayed it as black. I couldn't pick up items in these chunks. Apparently the world is completely broken for unknown reason. After making a new world it finally works and I can finally explore new biomes.

It isn't important to fix it I think because it was bugged out from the start and I just created a new world and continued so if still anybody is interested in testing a bugged world. [Here is the world](https://www.mediafire.com/file/i1ewysrvc17m5z9/main%2528%2529.zip/file)

**Comment by dandin87** [comment]
This may be related to an issue with Phosphor and updating to v0.7.0 may fix this world. Thanks for the download link. I will try and test it out later.
