### ISSUE TITLE
powdered/pulverized coal

### ISSUE THREAD

**Issue by tzaddi64** [TeamAOF/All-of-Fabric-3#248]
I need powdered/pulverized coal but can't make plates to get any power to grinder or make a lever.

**Comment by Yoosk** [comment]
You can make any plates without machines in `forge hammer`.

**Comment by tzaddi64** [comment]
There is no forge hammer.  The only forge is the conquest forge from Into the Omega, what or where ever that is.

**Comment by Yoosk** [comment]
Current version of the modpack does not have `Into The Ω` mod at all. Forge hammer is definitely there:
![2020-12-24_15-05-43-javaw](https://user-images.githubusercontent.com/4502802/103093081-3004fc00-45f1-11eb-8295-4743ab4f879f.png)

**Comment by tzaddi64** [comment]
New forge launcher didn't show an update. Thanks
