### ISSUE TITLE
Request: Please Add the these mods

### ISSUE THREAD

**Issue by EndlessEden** [TeamAOF/All-of-Fabric-3#25]
Seems like the best place to request these additions

_Since alot of the source links are not working for these mods, im providing their curseforge urls instead._

[Ynet](https://www.curseforge.com/minecraft/mc-mods/ynet): YNet is a mod based on the popular XNet by McJty, YNet allows you to transport items, fluids, energy and more on just one cable using a connector and controllers. For details, see the XNet documentation.

[LayingBox](https://www.curseforge.com/minecraft/mc-mods/layingbox): LayingBox adds resource chicken breeding, laying boxes and more. 

[LayingBox Vanilla Chicken Expansion](https://www.curseforge.com/minecraft/mc-mods/layingbox-vanilla-chicken-expansion): LayingBox Vanilla Chicken Expansion adds Vanilla resources chickens to the LayingBox mod. This mod also adds the following resources along with recipes to craft them into vanilla resources. Lava Nugget - combine in a ring around a bucket for a lava bucket, Diamond and Emerald Shards - combine in a ring around a slime ball for a Diamond/Emerald and Snowballs can now be combined in a ring around a bucket for a water bucket.

[Big Buckets: Fabric Edition](https://www.curseforge.com/minecraft/mc-mods/bigbuckets-fabric): This mod adds an upgradable bucket. It can store any fluid, and stores more than the regular bucket can. - NOTE: This was in the previous All-of-Fabric versions (2), but for some reason is not included in AOF3.

I have not tested these yet, but these all seem like solid additions to AOF3 that fit the theme and expected content. Thank You.

**Comment by Ectalite** [comment]
This one seems pretty cool too : [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod)

**Comment by martmists** [comment]
YNet author here. Currently the mod is a bit broken, I'm waiting for a library I'm using to become more stable for 1.16.1
Immersive portals won't be included since it creates a crazy amount of lag during portal creation.

**Comment by Ectalite** [comment]
Ok it‘s comprehensive, YNet would be praticle as there aren‘t a lot of ways to move fluids in this modpack.

**Comment by piegit** [comment]
I'm dropping a list of mods to add with their descriptions

https://www.curseforge.com/minecraft/mc-mods/lil-tater-reloaded

Lil Tater Reloaded is a mod that aims to do one, simple task: add Lil Tater into Minecraft.

https://www.curseforge.com/minecraft/mc-mods/mechanized-steam-power

Mechanized adds a variety of machines and gear all powered by a unique pressurized steam power system.

Play around with fans, breakers and placers, pumps and pistons.

Tinker with your tools and armor at the upgrade table.

Blast natural resources right out of the earth with the Steam Fractionating Tower.

https://www.curseforge.com/minecraft/mc-mods/bigbuckets-fabric

This mod adds an upgradable bucket. It can store any fluid, and stores more than the regular bucket can.

https://www.curseforge.com/minecraft/mc-mods/blockmeterfabric

It allows you to measure sizes of builds or areas so you can verify things line up the way you want, or having the distances they're expected to.

https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters

Client-side sound enchancing fabric mod.

 

Adds a few sound filters depending on your current location:

Reverb in caves and the nether
Muffled sounds when submerged in water or lava
Sounds become quieter when behind walls (Especially Wool or Sponge)

https://www.curseforge.com/minecraft/mc-mods/cartloaders

Cartloaders is a mod that allows any minecart* to load chunks it enters in an attempt to be more useful.

https://www.curseforge.com/minecraft/mc-mods/chatcalc

This can be very useful in building or crafting, as you will never need to risk mental math or need to pull out a calculator.

https://www.curseforge.com/minecraft/mc-mods/pumice

Clearing out lava in the Nether is a nearly impossible, grueling task. Not anymore!

**Comment by florensie** [comment]
[Egg Tab](https://www.curseforge.com/minecraft/mc-mods/eggtab-fabric)
Just updated this one properly for 1.16, it was in AOF2.

**Comment by jingshenSN2** [comment]
[Slab Helper](https://www.curseforge.com/minecraft/mc-mods/slab-helper)
This mod adds some simple ways that player can modify the slab block without breaking it, and it's very small and easy to use.

**Comment by LloydAZ** [comment]
[Leaf Decay](http://www.9minecraft.net/leaf-decay-mod/)

I really appreciate any pack that adds something like Fast Leaf Decay.

**Comment by Monster-Zer0** [comment]
Ynet: mod is super broken, the mod creator even suggests not using it yet.
LayingBox: not for 1.16.2 will research for 2.1
LayingBox Vanilla Chicken Expansion: same as previous
Big Buckets: Fabric Edition: not for 1.16.2 will research for 2.1 however, we had some issues in aof2 with this and is most likely why it hasn't been put back in.
egg tab: added in 2.0
slab helper: was introduced in 1.5.3
leaf decay: researching
