### ISSUE TITLE
Some Tech Reborn recipes only work with buckets and not cells

### ISSUE THREAD

**Issue by MarkKoz** [TeamAOF/All-of-Fabric-3#252]
For example, the 60k NaK Coolant Cell recipe requires sodium and potassium. The recipe will not work if cells containing those fluids are given, despite machines commonly outputting products as cells rather than buckets or pure liquid. This means one has to transfer the fluid out of a cell and into a bucket just to use it for crafting, which is tedious. REI is misleading because it shows recipes using cells when requesting to look at recipes needing the buckets. The opposite is true too - it shows recipes producing cells when requesting recipes that produce buckets.

Is this a bug or intentional?

**Comment by Jackthe3rd** [comment]
Intentional, techreborn cells are just one item changing its contents through nbt data. And there's no way to use nbt data in vanilla recipes (aka crafting table) without nbt crafting mod. so instead of adding new dependencies they do that. But i might be completely wrong
