### ISSUE TITLE
Crash when editing HWYLA config

### ISSUE THREAD

**Issue by danereinsch** [TeamAOF/All-of-Fabric-3#255]
Tried multiple times, when I try to edit the configuration of hwyla in the mod menu, both in and out of a session, it crashes the client. Looking at the crash report it is a null pointer exception after I clicked on the on-screen button. This may be more of an issue with the mod itself rather than the pack, but am posting it here too just in case.

**Comment by dandin87** [comment]
There is already a PR for HWYLA that fixes this issue. If you compile it yourself if does work. Just have to wait for th hem to accept the PR and update curseforge. You can use the config file to edit it as well.

**Comment by TrueCP6** [comment]
HWYLA seems to be abandoned. The last commit to the repo was 5 months ago, the PR has been open for nearly two months, and this can be found on the CurseForge page:
> I am no longer interested in modding.

The author of the PR has [a fork](https://github.com/badasintended/hwyla/tree/fabric-1.16.4) with [a release](https://github.com/badasintended/hwyla/releases/tag/pr-306) with this issue fixed.
