### ISSUE TITLE
AE2 & REI move items issue

### ISSUE THREAD

**Issue by Faustvii** [TeamAOF/All-of-Fabric-3#256]
When putting a storage bus on a ME interface like below

![image](https://user-images.githubusercontent.com/4357216/103243050-696e9c00-4950-11eb-90c4-51d3c6167c40.png)
moving items with REI recipe will "crash" the storage system. This only seems to happen after a certain amount of items exist in the ME storage.

Here's a little demonstration of how the issue looks like
https://user-images.githubusercontent.com/4357216/103243795-e26ef300-4952-11eb-8c5b-e284ea9869c3.mp4
and here is one without the storage bus connected on the interface
https://user-images.githubusercontent.com/4357216/103243824-00d4ee80-4953-11eb-9a44-d181c5075a5d.mp4

I'm playing on **AOF 2.5.4**, the only way to fix the AE system again is by restarting the server/reloading the world.

This is happening on the server I play on and I made a small single player world to demonstrate the issue, here's the attached world. 
[TestWorld.zip](https://github.com/TeamAOF/All-of-Fabric-3/files/5748761/TestWorld.zip)

**Comment by Yoosk** [comment]
It wont be fixed on modpack side, its not possible to do so. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4839

**Comment by Faustvii** [comment]
Thanks, I'll move to that issue.
