### ISSUE TITLE
Being on fire in nether for infinite time on server

### ISSUE THREAD

**Issue by pmalysYT** [TeamAOF/All-of-Fabric-3#258]
Is there a way to protect myself from that or a way to turn it off?

**Comment by Arcanocito** [comment]
I have been having the same issue even with full fire prot IV armors, it is extremely annoying :C

**Comment by ImAK9** [comment]
Pack version?

**Comment by Arcanocito** [comment]
We are on 2.5.4 at the moment still but will update to 2.5.7 today

**Comment by dandin87** [comment]
This bug has been around for a long time actually. I'm am unsure which mod is causing the issue. It is not just the nether I don't think, once you are on fire you have to step in water or be on fire indefinitely, or die.

**Comment by ImAK9** [comment]
Inb4 it’s Astromine

**Comment by ProjectET** [comment]
i think it was a vanilla bug iirc. Something to do with the height the portal was built.

**Comment by Shnupbups** [comment]
> 
> 
> Inb4 it’s Astromine

I'd be willing to bet it is, Astro does weird stuff to being on fire for some reason.

**Comment by ImAK9** [comment]
@dandin87 You willing to test this wonderful theory?

**Comment by dandin87** [comment]
Well, I can tell you that NA is on 2.5.7 now and I do not stay on fire indefinitely anymore. Odd. not sure about in the nether but I can test that later

**Comment by mcdodge34** [comment]
Anyone figured out something, I can't explore the nether right now because of this bug

**Comment by dandin87** [comment]
> i think it was a vanilla bug iirc. Something to do with the height of the portal being too low.

Its a vanilla bug unfortunately.

**Comment by mcdodge34** [comment]
I think I've got it sorted after using the gamerule to not get damaged by fire, I can get in fire fine, I can get in lava fine, and being extinguished when I get out, however if I was standing on soul sand or soul soil near lava, I can't extingish myself and need to go back in overworld and drop in water.
