### ISSUE TITLE
Nurishment icon doesn't show up in inventory interface when end chest is in inventory

### ISSUE THREAD

**Issue by djkiefer** [TeamAOF/All-of-Fabric-3#259]
Once I remove the end chest from my inventory, the nurishment icon shows up again.

**Comment by Twiixtor** [comment]
I have the same issue except the nourishment icon disappears when both a Crafting Table and an Ender Chest are in my inventory. When I drop one, the nourishment icon appears again. Just can't have two at the same time.

**Comment by erikkallen** [comment]
same issue here with 2.6.9 icon dissapears when end chest is in inventory

**Comment by erikkallen** [comment]
2.9.10 has the same issue

**Comment by Monster-Zer0** [comment]
still issue on 2.7.3 ?

**Comment by Monster-Zer0** [comment]
fixed with https://github.com/TeamAOF/All-of-Fabric-3/commit/c2b0bcb9ad7f7c45229f368087f0da61c84fd29f
