### ISSUE TITLE
Bring back the death chest

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#26]
The new gravestone mod is very confusing and error prone for someone that comes from forge, because (at least in the modpacks that I played) you had to break the gravestone to get all the items back. In this mod you have to stand on it? The forge version added a dirt block below the gravestone, so you did not fall through it, like you can in this mod (so you have to get blocks first, before you can get back your items).

The death chest on the other hand is very simple to understand and the items can be obtained very fast (even in places, where you have mining fatigue), which is why I would like suggest to bring back the death chest mod.

**Comment by dandin87** [comment]
Vanilla Death Chests do not put items in your trinket slots in them. They dropped on the ground and in the nether that means you lose them almost every time. Trinkets compatibility is a must. 

I can agree that the on step is annoying, however you can change the config to be ON_USE, ON_STEP, ON_BREAK and you can also specify how much xp you keep, and whether it puts the items back in your inventory or just drops it on the ground.

**Comment by AK9Official** [comment]
Could do https://www.curseforge.com/minecraft/mc-mods/better-graves ?

**Comment by dandin87** [comment]
That's basically the same mod. I would just change the Config to be either On_Use, or On_Break. Not sure which ppl want more, but the On_Step is pretty confusing.

**Comment by Geometrically** [comment]
Hey!
You can configure the mod in the config to change it to how you like it.

**Comment by Luro02** [comment]
The problem is that this is not the default behavior.

Most of the players that will try this modpack have already played with forge and are therefore already familiar with the concept of gravestones. (I might be totally wrong here, because I only played `Tekxit 3` and `The 1.12.2 Pack`, but both of them had gravestones so I think this common among modpacks). In those modpacks you get your items back by breaking the gravestone. When you do this in All of Fabric 3, you get a gravestone item that can be placed again, but the items that were associated with the gravestone are gone (even after placing it again). I had to search through the mod menu to discover that you had to step on it to get the items back.

Another issue is that the gravestone spawns quite frequently in the air (after you were blown up by a creeper or you died through fall damage), which makes it impossible to step on (you can't jump on it), without placing a block below it.

> You can configure the mod in the config to change it to how you like it.

If I configure the gravestone manually on my client, I don't think that the configuration would automatically apply to my server and configuring both the client and server is quite annoying (you would have to configure each client?) and after you update to a newer version of this modpack you would have to apply those changes again.


---

I really liked the death chest which made it possible to obtain the items even when you had mining fatigue.


This seems to be the repository for the death-chest mod:
https://github.com/TheRandomLabs/VanillaDeathChest/tree/1.16-fabric

I think I will make an issue there, so the author could fix the issue related to the ring dropping on the floor.

**Comment by Boundarybreaker** [comment]
> but the items that were associated with the gravestone are gone (even after placing it again)
this sounds more like a bug with the mod than a problem with the pack...

**Comment by Luro02** [comment]
> Vanilla Death Chests do not put items in your trinket slots in them. They dropped on the ground and in the nether that means you lose them almost every time. Trinkets compatibility is a must.

This is now fixed
