### ISSUE TITLE
Adding Mods

### ISSUE THREAD

**Issue by mndfrk** [TeamAOF/All-of-Fabric-3#260]
I wanted to add Mekanism as a mod to the pack but it doesn't load.

**Comment by ProjectET** [comment]
This is a fabric pack, the mod you are trying to add is a forge mod.

**Comment by mndfrk** [comment]
Oh Wow i am stupid. I didn't even notice. well i guess i gotta find another modpack then.

**Comment by MSandro** [comment]
https://github.com/BratishkaErik/Mekanism-Fabric
There is a Mekanism Fabric Port but it is in an early stage.
