### ISSUE TITLE
Client crash when using compressor from Tech Reborn

### ISSUE THREAD

**Issue by Chezzik** [TeamAOF/All-of-Fabric-3#263]
This probably could be sent to the Tech Reborn team, but I thought I'd post it here first just in case it is related to the combination of the mods in AOF3.

Shortly after opening the interface to the compressor, the client crashed.  I don't think the crash is repeatable.

The crash log is here: https://paste.ee/p/H5DAL

**Comment by Chezzik** [comment]
I've submitted this to Tech Reborn now also: https://github.com/TechReborn/TechReborn/issues/2324

**Comment by Monster-Zer0** [comment]
Thank you
