### ISSUE TITLE
Client crash while using spikes

### ISSUE THREAD

**Issue by aSemioticGhost** [TeamAOF/All-of-Fabric-3#266]
I started to build a mob farm for guardians, using spawners and kibe spikes for the grinder.
I consistently get a crash out with java.lang.IllegalStateException: Removing entity while ticking!
[crashdump.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5825602/crashdump.txt)

World was created with 2.5.7; crash occurs with both 2.5.7 and updated to 2.5.8.

The save where this happens should be obtainable at [this dropbox link](https://www.dropbox.com/s/53vfbnkts26gsmh/All%20Of%20Fabric%203.zip?dl=0)

Should be duplicatable by loading the save, heading to the rectangular mob-farm on the beach, and waiting for a guardian or witch to fall into the grinder.

**Comment by ImAK9** [comment]
Is this on a server? Because I see Damage Tilt which I’ve blacklisted from ServerStarter scripts installing.

**Comment by aSemioticGhost** [comment]
No, it's a single player world. I'm using AoF as it is out of the box - I can try disabling Damage Tilt when I next play.

**Comment by aSemioticGhost** [comment]
While it as taken me a while to get back here, disabling Damage Tilt as you mentioned resolved the issue.

My theory is that the guardians in the farm are taking 'player damage' due to the spikes, and have their thorns out, so it's attempting to invoke damage tilt on me.

As far as I'm concerned, this is resolved.

**Comment by Charles445** [comment]
Heya, I released a fix for this in DamageTilt 0.1.2, it should hopefully stop any more crashes like this.
