### ISSUE TITLE
Can't connect to server - Registry remapping failed

### ISSUE THREAD

**Issue by DarkSider8898** [TeamAOF/All-of-Fabric-3#269]
The server started correctly and there is no error. But if my friends and me want to join, we always get the same error:

![Bild_2021-01-20_182105](https://user-images.githubusercontent.com/64330126/105211188-42207e80-5b4c-11eb-8f1f-6c6c0af82d7a.png)

Please help

**Comment by DarkSider8898** [comment]
btw server version and client version are 2.5.7

**Comment by dandin87** [comment]
No, actually the server I believe is 2.5.7, and your clients are 2.5.9 as that is the error people who updated the pack would get when joining the server before it was updated.

**Comment by DarkSider8898** [comment]
Well, first I used client 2.5.9 and then switched to 2.5.7. I got the modpack from CurseForge; there I changed the version to 2.5.7. 

Update: While writing the comment I saw that the version was 2.5.9 ... I thought the whole time it was 2.5.7. That was a problem with CurseForge... 

Problem solved. thank you!
