### ISSUE TITLE
Identity menu broken

### ISSUE THREAD

**Issue by cncz42** [TeamAOF/All-of-Fabric-3#27]
Installed the new version of the modpack and all of the identities in the identity menu are grey squares, this doesn't seem to be a problem normally with the mod (and this is a fresh install of the modpack)

**Comment by Mivik** [comment]
As I noticed, turning off "Inmis" mod can solve this problem, but the reason remains unknown.

**Comment by Luro02** [comment]
I have the same issue

**Comment by siriusbtyt** [comment]
I confirm this issue.

**Comment by Luro02** [comment]
Note that the buttons themselves work fine and only the textures are broken.

**Comment by AK9Official** [comment]
Fixed in next update
