### ISSUE TITLE
anoying recipe conflicts

### ISSUE THREAD

**Issue by MSandro** [TeamAOF/All-of-Fabric-3#270]
![image](https://user-images.githubusercontent.com/10937159/105576516-7de95d00-5d73-11eb-93a7-51ca97a1d853.png)
![image](https://user-images.githubusercontent.com/10937159/105576533-9e191c00-5d73-11eb-88a8-4b2055eb1781.png)
Some Recipes e.g. Quartz have conflicts.
I've tested this in All of Fabric 3 - 2.5.9. 
I also tried this in an blank modpack with just Cinderscapes (and its dependencies) installed. and there the issue is not pressent. I think some Script or maybe an Mod which tries to implement some kind of OreDictionary could cause this.

**Comment by MSandro** [comment]
I can't find any workaround for Auto-Crafting...

**Comment by CrossWayIstaken** [comment]
The way that quartz is unified is really weird.
replaceInput('#c:quartz',  '#c:quartz') Is an awful way to do this, it should be more specific. All quartz variants should not be used in rose quartz block, sulfur quartz block recipes etc. Hope 2.6.0 will fix this

**Comment by Yoosk** [comment]
fxied in dev, mistake on our part

**Comment by CrossWayIstaken** [comment]
Nice!

**Comment by MSandro** [comment]
Solved since v2.6.0
