### ISSUE TITLE
Old version of GeckoLib makes Sodium crash

### ISSUE THREAD

**Issue by imreallybadatnames** [TeamAOF/All-of-Fabric-3#272]
Please update GeckoLib to the latest version for Sodium compatibility.

**Comment by dandin87** [comment]
AoF3 is not compatible with Sodium, except for with Comp500's fork and with Indium which adds the Fabric Rendering API. You can find links to the pack that include this on our discord.

**Comment by imreallybadatnames** [comment]
It does work successfully with new GeckoLib, though.
