### ISSUE TITLE
Game crash - Small or Large Tent in Bag (Campanion)

### ISSUE THREAD

**Issue by Witchlie** [TeamAOF/All-of-Fabric-3#273]
I can craft the tents and bags separately just fine, but the game crashes immediately after combining them to put them in the bag. Crash only occurs when trying to place the crafted item _into the inventory_ - as long as it is still attached to the cursor, the game functions fine. 
[Crash Log](https://github.com/TeamAOF/All-of-Fabric-3/files/5900403/New.Paste.1.txt)
Edited to add:
World can not be loaded again after this crash has happened - it will crash continually upon trying to start.

**Comment by Monster-Zer0** [comment]
please let the mod creator know.

**Comment by Monster-Zer0** [comment]
no response from op. closing issue.
