### ISSUE TITLE
Meta: Keep this GitHub releases updated.

### ISSUE THREAD

**Issue by DitDitGitHub** [TeamAOF/All-of-Fabric-3#276]
Some people, like me, are running Linux instead of Windows, which doesn't support CurseForge. It's a lot easier to download the MultiMC files from the GitHub then booting up Windows, downloading the files then switching back to Linux.

**Comment by dandin87** [comment]
Why would you do all of that? The zip is right here? Github is not the place we want people getting the pack from.
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3171408

**Comment by Technici4n** [comment]
Yeah, all zip files are available on CurseForge anyway, I always download them from there directly before importing to MultiMC.

**Comment by NinjaPhenix** [comment]
Could we get multimc specific releases on curseforge then? :eyes:

**Comment by UpcraftLP** [comment]
> Some people, like me, are running Linux instead of Windows, which doesn't support CurseForge. It's a lot easier to download the MultiMC files from the GitHub then booting up Windows, downloading the files then switching back to Linux.

just FYI, if you switch to the MultiMC beta you can directly import curseforge packs.

**Comment by dandin87** [comment]
> Could we get multimc specific releases on curseforge then? 👀 e.g. ones made to use fabric loader, not jumploader + forge.

How many download links do we need? MultiMC does not support a Curseforge like pack for fabric. Maybe if they used GD Launcher's way of supporting Fabric Loader it would be better. I imagine its going to be very close to however curseforge supports it. MultiMC having their own specific pack export is annoying. GD just changes the forge part to fabric. simple.
