### ISSUE TITLE
100% CPU while loading

### ISSUE THREAD

**Issue by andypop12345** [TeamAOF/All-of-Fabric-3#279]
i tried to play it for the 1st time with minecraft launcher, suddenly my PC is a turbine and task manager is telling 100% CPU usage and 90%+ of it is coming from MC launcher.. right.. How is this optimized for lower end pcs? its gonna fry mine

**Comment by andypop12345** [comment]
note: I was using curseforge launcher and downloaded it from there.

**Comment by Monster-Zer0** [comment]
use a pastebin site and post your logfile.

also.. don't "How is this optimized for lower end pcs?" us.. obviously this is a one off issue. but we need more info to be able to help you.

**Comment by velotican** [comment]
I started having this odd CPU usage behaviour after trying out 1.16 for the first time. I think this is a vanilla issue, actually. The client seems to hammer the CPU on initial load then ease off once everything's in memory and not bother it too much again after that.

**Comment by Monster-Zer0** [comment]
good point. also is normal game loading policy. moving to pending close unless OP has more to offer.
