### ISSUE TITLE
Adding OptiFine

### ISSUE THREAD

**Issue by BubblyBri** [TeamAOF/All-of-Fabric-3#280]
I seen another post about adding mods and how if it wasn't a fabric mod, it couldn't be done, this is my first time playing with them, so I know I'll learn as I go. But generally I add OptiFine to every modpack I have, and when I added it to my mod folder it of course acted like I hadn't. I'm assuming it's because of the reason above, but because it's a little harder for mine to run without it. I would love a solution on how to fix this.

**Comment by k3nw4y** [comment]
in Fabric, you need to add optifabric mod to use optifine
[Optifabric](https://www.curseforge.com/minecraft/mc-mods/optifabric)

**Comment by ALIAS-001** [comment]
I tried adding Optifabric to the modpack, but I get a mod conflict with lithium. 

error log: paste.ee/p/bR2oP

**Comment by dandin87** [comment]
There is an OptifiFabric/Optifine compatible zip on our discord in the #faqs channel. You can import it into any launcher that can use Curseforge packs, including the curseforge launcher. You just have to download and add the latest optifine from its website. The changes this pack has are; removing the Breaks with Optifabric check in lithium, removing the JMX mod, downgrading Ignus Fatuus to V1.1.0, and adding Optifabric.

**Comment by Monster-Zer0** [comment]
> 
> 
> I tried adding Optifabric to the modpack, but I get a mod conflict with lithium.
> 
> error log: paste.ee/p/bR2oP

then disable lithium
