### ISSUE TITLE
Items not loading in correctly

### ISSUE THREAD

**Issue by Starfish1010** [TeamAOF/All-of-Fabric-3#282]
Hi there I recently made a new server with the all of fabric mod 1.16.5. The server loads in but a ton of the items do not load in correctly. For example a ton of the trees are glitched with random blocks. Is there a way to fix this? When I chose the plug ins for the server I chose all of fabrics. I also play a single player with this mod pack and have 0 issues. Please let me know if something can be done. Also when I break the random blocks, the actual item it is supposed to be usually is whats in my inventory, but makes the whole world look odd.

**Comment by Monster-Zer0** [comment]
please use a pastebin site and post your log for this.

**Comment by Monster-Zer0** [comment]
changing to pending close as there has been no response
