### ISSUE TITLE
Battle Towers tools not behaving as tools

### ISSUE THREAD

**Issue by luxidoptera** [TeamAOF/All-of-Fabric-3#283]
Having an issue where the Battle Towers tools, with the sole exception of the Keyblade, do not seem to load correctly, being held in the hand like any other item instead of as tools and not applying their proper mining level to what they're being used to mine. Noticed this with the pickaxe in particular. The pickaxe seems to mine at the speed of a stone pickaxe without dropping blocks.

![image](https://user-images.githubusercontent.com/15697751/107116994-23f19880-6845-11eb-994e-d7b50e3e998d.png)
![image](https://user-images.githubusercontent.com/15697751/107116996-2bb13d00-6845-11eb-80ef-29cf7bc46430.png)

**Comment by Monster-Zer0** [comment]
mod dev has this issue added to their list

**Comment by Draylar** [comment]
Fixed in 3.3.3 of Battle Towers :)

**Comment by Monster-Zer0** [comment]
Thanks Draylar!
