### ISSUE TITLE
Opening some chests freezes the game

### ISSUE THREAD

**Issue by MyChoco17** [TeamAOF/All-of-Fabric-3#284]
I run around, game runs fine, and as soon as i open a chest, boom, the whole game stops. i can still move around, smooth 60 fps, but the problem is that i can't interact with anything in the world, open chests, break blocks etc, like the TPS is at 0, and it has happened twice, once with a barrel in an underground cave, and the second time in a battle tower. this resets all my progress to 0 as i cannot expect when to see a game breaking chest, and saving the world does nothing, as i left it for over an hour to save after a chest glitch, with nothing occuring. i think this might be a problem with the loot that might be inside the chests themselves

**Comment by Aquantis** [comment]
Me too, and i figured out it has something to do with chest containing enchanted books. i opened some stronghold library chest with no problem - none containing enchanted books. than i opened another one and the freeze happened. breaking the buuged chest also freezes the game, which points to the loot. other buuged chest i found were in crashed end ship - can spawn enchanted books, broken nether portal in the end -  can spawn enchanted books, and the library room in battle tower - also can spawn enchanted books. hope this helps.

**Comment by Monster-Zer0** [comment]
please use a pastebin site and paste your log for when this happened.

**Comment by Monster-Zer0** [comment]
changing to pending close as there has been no response
