### ISSUE TITLE
Parties not working

### ISSUE THREAD

**Issue by TheRealTorsk** [TeamAOF/All-of-Fabric-3#286]
So i wanted to play the new modpack with my girlfriend, but it says that parties are broken and therefor we cannot complete quests together. Was not sure if this was something you could fix or purhaps make so that when an item enters ones inventory, then the quest is completed for the player? Because right now we both have to make the item and then complete the quest.

**Comment by dandin87** [comment]
We will be transitioning to FTB quests which does have teams support. No eta, but it will be much eaiser/better to use than HQM

**Comment by Monster-Zer0** [comment]
known bug with the mod (Hardcore Questing Mod)
