### ISSUE TITLE
[AoF3-2.6.4] Client Crash when Dying

### ISSUE THREAD

**Issue by Elvarion** [TeamAOF/All-of-Fabric-3#287]
Client crashed when dying
Brand new world, spawned near a battle tower, some guardians killed me while climbing a ladder.
Was able to re-produce it twice when doing the same thing.

https://paste.ee/p/GGhf6

**Comment by ImAK9** [comment]
Fixed in 2.6.5
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3204728
