### ISSUE TITLE
Make a direct download link

### ISSUE THREAD

**Issue by Qwart376** [TeamAOF/All-of-Fabric-3#289]
Linux users are locked out and CurseForge app is barely useful. It's not even worth installing Wine and getting it to work. 
Thanks in advance

**Comment by ImAK9** [comment]
There already are direct links.
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3204728
Click the download button.

**Comment by Qwart376** [comment]
> There already are direct links.
> https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3204728
> Click the download button.

That's a 2 mb zip file you need run through multimc that sells your data to google, I'm asking for a serverpack that anyone can run

**Comment by florensie** [comment]
MultiMC is FOSS software. So is GDLauncher if you want another option.

**Comment by florensie** [comment]
> I'm asking for a serverpack that anyone can run
This is not possible because of some of the mod's licenses.

**Comment by Technici4n** [comment]
> multimc that sells your hardware info to google
Source?
