### ISSUE TITLE
Pine slabs are uncraftable.

### ISSUE THREAD

**Issue by siriusbtyt** [TeamAOF/All-of-Fabric-3#29]
A bunch of items cannot be crafted because for some reason pine slabs are uncraftable. I would love to craft pine chairs and more but yeah I cannot.

Additionnal mods added to the mod pack (client side):
- Sodium
- Replay Mod

Here's many screenshots:
![2020-07-31_11 43 13](https://user-images.githubusercontent.com/60975935/89023077-4b5e2a80-d323-11ea-8f67-d085e16f19de.png)
![2020-07-31_11 43 26](https://user-images.githubusercontent.com/60975935/89023086-4dc08480-d323-11ea-8aea-245132c76358.png)
![2020-07-31_11 43 41](https://user-images.githubusercontent.com/60975935/89023092-4ef1b180-d323-11ea-8836-64b09a53f787.png)

**Comment by AK9Official** [comment]
Fixed in next update.
