### ISSUE TITLE
the game wont open

### ISSUE THREAD

**Issue by mindoindo** [TeamAOF/All-of-Fabric-3#293]
When I pressed the play button, I waited a few minutes for a long time, and the game won't open. It's like it's not even running

**Comment by mindoindo** [comment]
nvm i just figured out i had to be a bit more patient

**Comment by mindoindo** [comment]
and now its stuck on the loading screen .-.

**Comment by atreydesai** [comment]
How much ram did you assign? Recommended is 4 GB.

**Comment by mindoindo** [comment]
sorry i didnt see earlier and wdym by assigning 4 gb? all I did was click play once the launcher poped up

**Comment by Monster-Zer0** [comment]
https://github.com/TeamAOF/All-of-Fabric-3/wiki/Running-AOF3[view this](url)
