### ISSUE TITLE
Troubles with Industrial sawmill/Industrial blast furnace.(help please)

### ISSUE THREAD

**Issue by WarMachine165** [TeamAOF/All-of-Fabric-3#294]
I have attempted to figure out how these two work for a whole day. I know that the blast furnace is a 3x3x4 in machine casings and the sawmill is a 3x3x2, I also know that you're supposed to put lava in the two holo spaces in the middle with the blast furnace and a water block in the one holo space in the sawmill. For power, I am using three ultimate solar panels and 4 battery blocks. I am following the Hologram in-game so I don't understand why it isn't working.
(I have also tried to use different casings in creative and it still didn't work)
Anyone else have the same issue?

**Comment by ImAK9** [comment]
It's a known bug and will be fixed in 2.6.7

**Comment by WarMachine165** [comment]
> It's a known bug and will be fixed in 2.6.7
So is there any way to fix the bug as far as you know?

**Comment by WarMachine165** [comment]
or do I have to wait

**Comment by Monster-Zer0** [comment]
2.6.7 is out

**Comment by WarMachine165** [comment]
> 2.6.7 is out

Awesome
