### ISSUE TITLE
IndRev can't accept EU power from Tech Reborn

### ISSUE THREAD

**Issue by Porcy** [TeamAOF/All-of-Fabric-3#296]
Just updated to 2.6.7. All my indrev machines connected to TR cables are out of power. Cables from TR won't connect. Even my modular armor from indrev doesn't recharge from a TR Lapotronic Energy Orb. Tried indrev latest Beta (1.8.5) to no avail.

**Comment by GabrielOlvH** [comment]
This isn't a bug, indrev now uses a different energy api from TR's. Indrev's cables can still use use and supply power to TechReborn but not the other way around.
