### ISSUE TITLE
Can't charge jetpack in LF Container MK1

### ISSUE THREAD

**Issue by dyerseve** [TeamAOF/All-of-Fabric-3#299]
2.6.9 after upgrading from 2.6.3 we cannot seem to charge our jetpacks, I thought maybe it was a tiered thing but even the wooden one wouldn't charge in a mk1.
The items literally won't go into the LF Container. The drills and things in the same mod work but something in the cross mod compatibility stopped working in this upgrade.

**Comment by ImAK9** [comment]
Fixed in 2.6.10
