### ISSUE TITLE
Fabric Furnaces are seriously overpowered (Semi-Automatic Mineral Duplication)

### ISSUE THREAD

**Issue by siriusbtyt** [TeamAOF/All-of-Fabric-3#30]
I have here a machine that abuses the hell out of the **Fabric Furnace's duplication feature**. By **grinding** for example **diamonds** you get **diamond dust**. Then you **cook it** and you have **a single diamond**. But starting from the **emerauld furnace**, the furnace can **dupe anything that is cooking inside**. You see were this is going. By doing a bit of Minecart, redstone stuff, you can make it 90% Automatic _(You have to watch out for the lava buckets.)_ This is fine until you realise **you can dupe netherite as much as you want**. (You have to use _a different machine_ however.) This is amazing and not amazing that you can do that. (Since yay ! Less farming !) This is fine if you are on single player however on a server **trading with thoses minerals are basicly useless**. The ONLY thing that **cannot be duped** (and that is a seriously good & rare mineral) **despite being on a dust form** is the **Vibranium**. Whatever you do, I would like to keep the furnace features except **nerf a lot the duping chance**. or **removing the duping**. Though the problem is that you need to contact the modder that made this mod if you guys decides to keep it.

![2020-07-31_13 43 16](https://user-images.githubusercontent.com/60975935/89032073-1efeda00-d334-11ea-820f-4774cc37922a.png)

**Comment by AK9Official** [comment]
I’ll make sure to rebalance it for next update

**Comment by AK9Official** [comment]
@Draylar You should honestly reconsider nerfing the duping by default

**Comment by AK9Official** [comment]
Fabric Furnaces can no longer duplicate output. Will be added in next update.

**Comment by siriusbtyt** [comment]
The "next update" (even on 1.5.1) still has furnace duping. Is this config file related ?
