### ISSUE TITLE
I can't find diamonds what the fuck?

### ISSUE THREAD

**Issue by Garueri** [TeamAOF/All-of-Fabric-3#301]
I mined around 2000 blocks multiple times on the 12Y level, one at the woodlands biome and another at the meadow biome, this is getting really frustrating since I can't progress without a good amount of diamonds
What am I doing wrong?
I'd like to report that mods like BYG, Ecotones, and the mod that changed the cave systems are really annoying me, this has been killing a lot of my experience in the modpack because it sucks to mine. Everywhere I go, I find gigantic obsidian caves, lava lakes, and water caverns, BYG made my nether a true hell, extremely hard to find a fortress and the fear that resources don't spawn on given biomes is killing my will to play, how do i find god dam diamonds? Am I dumb? Probably, plz help

**Comment by Garueri** [comment]
Ok i literally just mined an entire chunck, and i ONLY found 3 god dam diamonds, is this normal?

**Comment by ProjectET** [comment]
you are probably unlucky, i found like 2 stacks of diamonds from YUNG's caves

**Comment by Garueri** [comment]
Ok I took some time off and I have something alike to a solution
Use the mod called @biomelocator, it has an item probably with the same name. The recipe is a map surrounded by rabbit leather, you can find a lot of rabbit on deserts, go to a big desert or gather 2 rabbits using carrots and start procreating, if you want carrots, I recommend looking around for a battle towers tower dungeon where you will find many many zombies, and kill them until you gather carrots.
After making a biome locator look for any biome that has Minecraft as the mod of origin, inside Minecraft created biomes it seems like the ore spawn is ok, I'm not sure for the rest, as I said, I mined an entire chunk and only found 3 goddam diamonds, that's total bullshit to me.
Mining at a Minecraft biome I was able to find way more diamonds with way less mining than I was having, though it's still a very small amount considering I have a Giga drill
