### ISSUE TITLE
With MultiMC launcher All-of-Fabric frequently fails to start

### ISSUE THREAD

**Issue by duncanwebb** [TeamAOF/All-of-Fabric-3#302]
### Pack version
All-of-Fabric-3-2.6.3
### LWJGL 3
3.2.2
### Minecraft version
1.16.5
### Intermediary Mappings
1.16.5
### Fabric Loader
0.11.1

I'm having trouble running the pack. Sometimes the pack starts and works just fine and other times it fails to start with messages like:
The specified resource 'fabric-rendering-data-attachment-v1.mixins.json' was invalid or could not be read
The specified resource 'libstructure.mixins.json' was invalid or could not be read

The debug.log is: https://pastebin.com/6bzzHgxY
There is no crash log

I'm using MultiMC 0.6.11 and not sure what is causing the pack to fail, if it is the pack or MultiMC.

Hopefully, someone can help. TIA

**Comment by duncanwebb** [comment]
On every launch of this day the failure line cycled through the following missing json files

**The specified resource 'message' was invalid or could not be read**

* magna.mixins.json
* mixins.playerabilitylib.common.json
* tweed.mixin.json
* mixins.reach-entity-attributes.json
* mixins.cardinal_components_level.json
* fabric-rendering-fluids-v1.mixins.json
* tweed.mixin.json
* megane-impl.mixins.json
* fabric-registry-sync-v0.mixins.json
* mixins.terraform-dirt.json
* fabric-containers-v0.accurate.mixins.json
* fabric-particles-v1.mixins.json
* mixins.terraform-dirt.json
* fabric-game-rule-api-v1.mixins.json
* mixins.mm.json
* fabric-command-api-v1.mixins.json

The following day I could run that pack first time, I'm not certain if this is because of a machine reboot or that some files were changed on the Minecraft end, the updating assets index... line was reasonable long when the pack started.

I also created a new fabric instance with just a few mods
* architectury-1.5.112-fabric.jar
* fabric-api-0.30.3+1.16.jar
* light-overlay-5.6.1.jar
* mousewheelie-1.6.4+mc1.16.4.jar

And this also failed to start as described above, but today it does start.

So, my conclusion is that this is not a pack error but lies somewhere else possibly to do with the fabric loader. I raised the ticket because this error has happened more than once on different days.

**Comment by Monster-Zer0** [comment]
I would try to use the new fabric api and see what that gets you

**Comment by duncanwebb** [comment]
> I would try to use the newest fabric api and see what that gets you

Doesn't seem to make a difference, thanks for the suggestion.

Yesterday I installed the 2.6.10 version of the pack and played it all afternoon without any problem. What I do is add a new instance and install from a zip file, copy over the save and waypoints and play start the new game.

This morning I started the game, and it failed with the message:
`Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-screen-handler-api-v1.mixins.json' was invalid or could not be read`

Checking the MultiMC settings, it shows that the Forge is installed instead of the Fabric loader. Removing the Forge loader and installing the Fabric loader, the game still failed to start, as above. Rebooting the computer and it runs successfully.

What I find strange is, why did the game play yesterday with the forge loader installed?

Maybe a restart of MultiMC is sufficient instead of a reboot.

Why does MultiMC installed Forge instead of fabric? I'll ask this question on the MultiMC issue tracker.

**Comment by duncanwebb** [comment]
The manifest.json has the following:
```
{
  "minecraft": {
    "version": "1.16.5",
    "modLoaders": [
      {
        "id": "forge-36.0.13",
        "primary": true
      }
    ]
  },
  "manifestType": "minecraftModpack",
  "manifestVersion": 1,
  "name": "All of Fabric 3",
  "version": "2.6.10",
```
Which explains why forge is being installed.

**Comment by supsm** [comment]
> Why does MultiMC installed Forge instead of fabric?
AOF supports the twitch launcher, which is forge, so it uses jumploader to launch fabric from forge. Since you are downloading the twitch launcher zip file, you are installing forge with jumploader instead of fabric. If you want, you can change forge to fabric in MultiMC and remove jumploader.

**Comment by duncanwebb** [comment]
Thank you for that explanation, it helps a lot. It is a bit confusing when you don't know this. 

I have done as you said, and it helped a lot, it fact I've had no failures starting the games for the last few days. 

I also disabled "mousewheelie" as the logs were complaining about a conflict. Not sure is this is necessary, just have to click a bit more.

**Comment by duncanwebb** [comment]
One more observation, when the pack is started after running other applications like brave browser, thunderbird, etc it fails to load. If MultiMC and the pack is started first thing after a boot it works.
