### ISSUE TITLE
Sometimes the same item is not stackable, because of invalid NBT metadata

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#31]
![Screenshot_20200802_111031](https://user-images.githubusercontent.com/24826124/89119770-167fde00-d4b1-11ea-90d5-646da8ce0acd.png)
![Screenshot_20200802_111035](https://user-images.githubusercontent.com/24826124/89119774-1a136500-d4b1-11ea-869d-3f04759b4fca.png)
![Screenshot_20200802_111136](https://user-images.githubusercontent.com/24826124/89119777-1aabfb80-d4b1-11ea-82dc-67bf2dca364c.png)
![Screenshot_20200802_111139](https://user-images.githubusercontent.com/24826124/89119778-1b449200-d4b1-11ea-80bd-c1c47897cb6e.png)

[NBT Tooltip](https://www.curseforge.com/minecraft/mc-mods/nbt-tooltip) has been used to inspect the item metadata (in-game) and the below screenshot is from NBT Explorer.

![Screenshot_20200802_111611](https://user-images.githubusercontent.com/24826124/89119854-ad4c9a80-d4b1-11ea-9fef-3e56f8e83ef0.png)

[playerdata.zip](https://github.com/TeamAOF/All-of-Fabric-3/files/5011896/playerdata.zip)

**Comment by AK9Official** [comment]
Not even sure on what mod could do this.. I'll look into it.

**Comment by Shnupbups** [comment]
Oh no... this looks like what NBT Crafting used to do anytime you put something in a crafting slot...

Not pointing fingers, but I am potentially providing a place to start looking.

**Comment by cutezyash** [comment]
Yeah I keep having this problem with my game, 10% of my items are duplicates of another of the same item. It's very obnoxious. It happens a lot especially when trading with villagers.

**Comment by AK9Official** [comment]
I have no idea what’s the cause, I’ll look into it.

**Comment by gharris1727** [comment]
I've also seen this happen with wheat after feeding cows.

**Comment by MattBee2k2** [comment]
Just to chime in too, it happens with torches and I believe it's when different wood is used for the sticks but not 100% sure if that was one of the causes.

**Comment by Luro02** [comment]
It also happens with seeds and wheat.

**Comment by Sabster** [comment]
torches as well - ones I picked up are different from the ones I crafted.  I had to create a bunch of torches, place them on the ground and then pick them back up.

**Comment by Luro02** [comment]
It also happens with villager trading. The emeralds you get from villagers, sometimes cannot be merged with old ones.

**Comment by MaryHeadpoppins** [comment]
from what i've seen droping items and picking them up should cause them to stack

**Comment by AK9Official** [comment]
fixed
