### ISSUE TITLE
AE2 crank obtainable, but grindstone is not

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamAOF/All-of-Fabric-3#317]
AE2's wooden crank can be crafted through its recipe or obtained as a reward for the quest *"Charge yer crystal.. man"* despite the AE2 quartz grindstone being unobtainable, making the crank useless, as it can't even be placed on anything but the quartz grindstone.

**Comment by Monster-Zer0** [comment]
it can be used on the charger. it's a joke also.
