### ISSUE TITLE
You cannot fly when you're an Ender Dragon. Also this happens.

### ISSUE THREAD

**Issue by siriusbtyt** [TeamAOF/All-of-Fabric-3#32]
Cannot put tags but from what I see the tag should be "Mod issue".
Also I have wings so I can't tell if you have the wing effect when being an Ender Dragon.

![image](https://user-images.githubusercontent.com/60975935/89120744-0409a280-d4b9-11ea-9ea7-b3e425912a96.png)

**Comment by AK9Official** [comment]
flying is turnt off for Identity.

**Comment by AK9Official** [comment]
Pretty sure wings wont apply the effect on top of Identity.. It kinda should but I don't think it does.

**Comment by siriusbtyt** [comment]
Uhhh Flying works with Identity, you can fly as a bat for example. Well it works on the server i'm on at least.
