### ISSUE TITLE
Tech Reborn Quests

### ISSUE THREAD

**Issue by duncanwebb** [TeamAOF/All-of-Fabric-3#321]
### Version 2.6.10

The quests for the Industrial Grinder and the Industrial Blast Furnace are the wrong way around. The Industrial Grinder needs steel which is made in the Industrial Blast Furnace. Also, the grinder needs advanced machine casings.

I realize that you can get steel dust from scrap boxes, but this is a bit hit-and-miss.

As an aside:
The electric tree tap is more helpful early on so being the first of the electric tools would be nice. Same with the grinder as this gives early ore doubling and so is more useful than the electric furnace and could be first in this chain.

Thanks very much for the pack, I'm having a load fun playing the pack.

**Comment by gildervine** [comment]
little addendum .. the quest top tier blocks in the tech reborn category requires 1 advanced machine casing, while it should require 1 industrial machine casing, i guess

**Comment by MeTaNoV** [comment]
very nice suggestions

**Comment by duncanwebb** [comment]
Thanks for the new quests, a welcome update. 

Slightly off-topic, the first quest in Applied Energistics is to get charged certus quartz and the reward is a wooden crank for use in the grindstone. However, you cannot craft the grindstone, so maybe a different reward would be better.
