### ISSUE TITLE
Dank middle click sort

### ISSUE THREAD

**Issue by Manw1ch** [TeamAOF/All-of-Fabric-3#325]
When using the middle click sort function on a dank it will delete items in stacks of over 64 if there are multiple of the same item.
![before](https://user-images.githubusercontent.com/81663279/113081716-075f4600-918e-11eb-8b8c-d0d1bdfe82d7.png)
![After](https://user-images.githubusercontent.com/81663279/113081723-09c1a000-918e-11eb-8e6f-28582ac1c941.png)

**Comment by kabadesu** [comment]
What you need to do is edit your `config/inventorysorter/blacklist.json` to look like this

```
{
	// Inventories that should not be sorted
	"blacklistedInventories": [
		"tfar.dankstorage.client.screens.DockScreen",
		"tfar.dankstorage.client.screens.PortableDankStorageScreen"
	]
}
```
Middle-click to sort will function normally after that.
