### ISSUE TITLE
I just started with this mod pack and textures not loading correctly

### ISSUE THREAD

**Issue by coolayaansh** [TeamAOF/All-of-Fabric-3#326]
I get purple and black boxes in most of the items
instead of the correct textures and I cant find any texture packs that cover all the items in this texture pack

**Comment by Monster-Zer0** [comment]
Lemme guess. You're using sodium. Tis why we don't put sodium in the pack in the first place. Go to our discord to the #faqs section and download the sodium+indium we have listed there. Use that instead

**Comment by coolayaansh** [comment]
For some reason i cannot Join the discord server

**Comment by coolayaansh** [comment]
Was hoping you could add me 
coolbroayaansh#2507

**Comment by kabadesu** [comment]
What's your Minecraft username?
