### ISSUE TITLE
Load up aof 3 today and textures not loading up

### ISSUE THREAD

**Issue by Folski** [TeamAOF/All-of-Fabric-3#329]
My textures are not loading up
![image](https://user-images.githubusercontent.com/79508150/114182637-c0fea980-993a-11eb-80cb-ceb7490325bb.png)

**Comment by Monster-Zer0** [comment]
im assuming you added sodium. if not please let us know what textures are not showing up.

if using sodium, use the sodium+indium in the #faqs on our discord. otherwise you will have render issues.
