### ISSUE TITLE
Can't Make Cheese

### ISSUE THREAD

**Issue by Zoltab** [TeamAOF/All-of-Fabric-3#330]
I have an online server with All of Fabric 3 modpack and i can't craft cheese from "Sandwichable" mod.
Cheese is made by pouring milk into a basin and by waiting 3 mins, but when i do that nothing happens.

**Comment by ProjectET** [comment]
You need cheese culture as well that's why you are not getting cheese.

**Comment by Zoltab** [comment]
You're right, i didn't see anything on the mod page. Thank you for your answer
