### ISSUE TITLE
up-to-date driver

### ISSUE THREAD

**Issue by ochmaneyy** [TeamAOF/All-of-Fabric-3#334]
Hello everyone, I recently had a problem that when I open All of Fabric 3, the message "up to date driver" and then it does not open. However, I already have my drivers up to date and have been looking for updates. However, it still doesn't work. Can someone help me?

**Comment by Monster-Zer0** [comment]
still an issue?

**Comment by ochmaneyy** [comment]
i dont have curse forge anymore but it was still there.

**Comment by Monster-Zer0** [comment]
Do you mean you can do it again with curseforge.. but now you can't when using a different client?

**Comment by Monster-Zer0** [comment]
moving to pending close as no response from op
