### ISSUE TITLE
Game lags for couple seconds after crafting >10 items 

### ISSUE THREAD

**Issue by atreydesai** [TeamAOF/All-of-Fabric-3#338]
When crafting a stack of anything for example, when shift-clicking to put the stack into inventory, one will move, the other 63 will persist in the product slot of the crafting table, then after like 4 or 5 seconds, the other 63 will move to your inventory. (Courtesy of Clover). 

The lag increases based on the number of items used to craft that item and how many of the item the user shift-clicks into the inventory.

This problem has existed for a long time. The earliest I can remember is the 2.4.0 versions.

Steps to Reproduce:
1. Get 9 stacks of iron ingots
2. Put in crafting grid and shift-click the iron blocks
3. One should appear in the inventory and the rest will appear after 2-3 sec of lag.

This issue does not seem to appear on the AE2 crafting panel. 

In case it's helpful: 2019 Mac running MultiMC.

**Comment by Monster-Zer0** [comment]
sp or mp? and if mp.. is it the aof public servers?

**Comment by atreydesai** [comment]
SP. Haven't test on MP.

**Comment by Monster-Zer0** [comment]
could be related to sorting issues.

**Comment by atreydesai** [comment]
It was with the regular crafting table.

**Comment by HueboWasTaken** [comment]
this problem can be fixed by adding the FastBench mod to the pack
