### ISSUE TITLE
Sleaping in a coffin of Bewitchment Mod doesnt toggleit to night. 

### ISSUE THREAD

**Issue by TimspieltGG** [TeamAOF/All-of-Fabric-3#339]
When you are sleeping in a coffin it turns it to morning so playing as an Vampire doesnt make any fun.

**Comment by Monster-Zer0** [comment]
I think bewitchment fixed this recently. need to verify.

**Comment by MoriyaShiine** [comment]
I fixed this as of https://github.com/MoriyaShiine/bewitchment/commit/f32f3c9ff89bdbf57ea7b0ba863269b3d5df45a2, build will be on curseforge soon :ok_hand:

**Comment by Monster-Zer0** [comment]
> 
> 
> I fixed this as of [MoriyaShiine/bewitchment@f32f3c9](https://github.com/MoriyaShiine/bewitchment/commit/f32f3c9ff89bdbf57ea7b0ba863269b3d5df45a2), build will be on curseforge soon 👌

you're the best. thank you!
