### ISSUE TITLE
Weird alignment at the title screen on the highest GUI scale value

### ISSUE THREAD

**Issue by profjb58** [TeamAOF/All-of-Fabric-3#341]
Think the picture describes it all
![image](https://user-images.githubusercontent.com/46009144/116002411-9296f480-a5f1-11eb-943d-d4d2a94203c0.png)

**Comment by Monster-Zer0** [comment]
hmmm, Idk if slight gui modifications has an ability to scale. we can look into it

**Comment by Monster-Zer0** [comment]
slight gui modifications only does absolute size. not a percentage or any way to do scaling. not as far as I can tell.
