### ISSUE TITLE
the server file is containing a virus ?

### ISSUE THREAD

**Issue by NaiSan70** [TeamAOF/All-of-Fabric-3#342]
when i try to extract all of the content for the start server.bat file it says that there is a virus and that i cant extract it.

**Comment by NaiSan70** [comment]
this is the virus name ''r Heur.BZC.ONG.Leopard.1.145644C1''

**Comment by dandin87** [comment]
There is no virus. Curseforge would not be hosting the file. This is a false positive or it did not come from the curseforge website

**Comment by NaiSan70** [comment]
but i still cant exctract the file

**Comment by dandin87** [comment]
You need to tell your antivirus software to ignore that file, or disable the antivirus software. I don't know your software, nor do I use antivirus aside form Windows Defender. there is no need.
