### ISSUE TITLE
Can't craft BLAST stripminer without cheating

### ISSUE THREAD

**Issue by ironsnake345** [TeamAOF/All-of-Fabric-3#343]
Simply put, when trying to craft gunpowder blocks, Charm's gunpowder block takes priority over BLAST's, making the BLAST gunpowder block uncraftable. Since they are required to make BLAST stripminers, this means that, by extension, BLAST stripminers can't be crafted without cheating.

**Comment by nickavem** [comment]
I have an open pull request (#340) if you want to give that config change a chance.

**Comment by ironsnake345** [comment]
I kind of like that compromise, yeah. Although, A: I feel like it should allow a coal block or charcoal block for the recipe, and B: I wish I knew how to change configs.

**Comment by Monster-Zer0** [comment]
fixed with @nickavem 's commit https://github.com/TeamAOF/All-of-Fabric-3/commit/609b98f07f7f25213bfa066b5f3d5de5c7acff16

will be in next version
