### ISSUE TITLE
Not a problem , but can somebody help?

### ISSUE THREAD

**Issue by hunterproasd** [TeamAOF/All-of-Fabric-3#344]
Hey guys , I'm just wondering that after the latest 2.7.2 patch , my recipe book disapeared , which mod causes it , or can I make it reappear ? 

Looking forward for your answers.

**Comment by Monster-Zer0** [comment]
idk mod would cause that. I would double check that rer is installed.. check the mods menu and see if it's there and also check the settings for rer (roughly enough resources) in said mod menu to see if it's not disabled somehow.

**Comment by hunterproasd** [comment]
I'll give that a try , thank you man, appriciate it.

**Comment by hunterproasd** [comment]
That was it, thank you very much

Monster Zero ***@***.***> ezt írta (időpont: 2021. ápr. 26.,
H 19:22):
