### ISSUE TITLE
Shaders??

### ISSUE THREAD

**Issue by SutekiRedux** [TeamAOF/All-of-Fabric-3#346]
Noticed in showcase images you used shaders, but I can't seem to find a way to add shaders to the mod pack since it runs with lithium. Do I remove lithium from the server side before I can add optifabric? or is there a different way to run shader packs?

**Comment by dandin87** [comment]
In our discord in #faqs channel is a zip to you want to extract into the instance root folders. The one that has the mods and config folder. This will overwrite mods and a config file that will allow you to load with optifine. The lastest Optifine G8 is recommend.
