### ISSUE TITLE
World crashed upon death, now I cant load the world

### ISSUE THREAD

**Issue by MontiBro** [TeamAOF/All-of-Fabric-3#348]
I died in my solo survival world and the game crashed. Upon relaunching the game I got a crash report and now I cant start up the world at all without it crashing directly after it loads. Is there any way to fix this? We just got put in another full lockdown so I was hoping to play some AOF3 to pass the time. Thanks!
[crash-2021-04-28_12.49.09-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/6393165/crash-2021-04-28_12.49.09-server.txt)

**Comment by SnugglebunnyX** [comment]
This is also happening to me. It has happened multiple times since the new update- https://pastebin.com/JZpma60h

**Comment by dandin87** [comment]
First one appears to be hardcore questing mode which was Removed in 2.7.0 of you updated to 2.7.0 delete HQM from the mods folder, it should not be there.

**Comment by dandin87** [comment]
> This is also happening to me. It has happened multiple times since the new update- https://pastebin.com/JZpma60h
This one might be RER. Delete it from the mods folder on the server. It will be removed in the next update until it is fixed.

**Comment by SnugglebunnyX** [comment]
I'll give it a whirl. Thank you :)

**Comment by MontiBro** [comment]
I downgraded then updated my launcher and moved a copy of the broken save to the new client, it somehow worked and I have access to my world again but I don't think its a reliable solution to the issue.

**Comment by dandin87** [comment]
This is more an issue with curseforge launcher failing to update the instance correctly. The solution is to not use their faulty launcher and use GD Launcher which has the ability to update modpack versions, and doesn't mess it up all the time like curseforge launcher. MultiMC unfortunately does not have that feature.

> I downgraded then updated my launcher and moved a copy of the broken save to the new client, it somehow worked and I have access to my world again but I don't think its a reliable solution to the issue.

**Comment by SnugglebunnyX** [comment]
Getting rid of RER did resolve my issue and my server is running smoothly again. Thank you again!
