### ISSUE TITLE
Certain blocks cannot be picked up

### ISSUE THREAD

**Issue by davidthehat** [TeamAOF/All-of-Fabric-3#35]
When mined in survival, certain blocks don't drop anything when mined.

The affected blocks include:
- Tech Reborn ores
- All Adabranium blocks
- All Industrial Revolution blocks
- Cinderscapes ores

**Comment by AK9Official** [comment]
Are you using Adabranium tools?

**Comment by davidthehat** [comment]
It happens with all tools. With more testing, all industrial revolution blocks are affected as well.

**Comment by AK9Official** [comment]
Let me look into it..
