### ISSUE TITLE
Unable to trade with some mods villagers

### ISSUE THREAD

**Issue by mandrin92** [TeamAOF/All-of-Fabric-3#350]
Currently (AOF3 2.7.2) unable to trade with
- Sandwich Maker of Sandwichable (v1.7.1)
- Traveller of Dungeons Mod Lite (v1.16.5-1.0.0)
No problem with Vanilla and Charm (v2.3.2) ones.

**Comment by dandin87** [comment]
This is an issue with Fabric API and will be resolved when FAPI updates.
https://github.com/FabricMC/fabric/pull/1430

**Comment by mandrin92** [comment]
Okay, thank you. (I close this thread and watch the FabricMC thread)
