### ISSUE TITLE
Charm Golden Bars conflict with Blockus golden bars[BUG]

### ISSUE THREAD

**Issue by dandin87** [TeamAOF/All-of-Fabric-3#355]
**Is this a modpack or mod issue?**
(if something is screwy using a certain mod, then send the bug to the mod dev first.)
Modpack
**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**

**Modpack Version**
(any bugs using a non-up-to-date version will be asked to replicate with the most up-to-date release)
all

**Describe the bug**
Only charm gold bars can be crafted. blockus golden bars cannot as they share the same recipe. Monster PLEASE FIX, you are our only hope!!!

**To Reproduce**

**Expected behavior**
I expect only the most highest quality of modpack makers making those handcrafted artisanal recipes to resolve these kinds of conflicts.
**Screenshots**

**Logs**
(you can use https://paste.alloffabric.com)

**Additional context**

**Comment by Monster-Zer0** [comment]
Is this really a thing?

**Comment by dandin87** [comment]
yes. A few players have brought it up. you could just make the recipe 1 charm golden bars = 1 blockus golden bars

**Comment by Monster-Zer0** [comment]
https://github.com/TeamAOF/All-of-Fabric-3/commit/246e9ba8a25f1073e22eee42e7ca3f9567766d9b fixes this
