### ISSUE TITLE
[BUG] Grammar errors in new quests

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamAOF/All-of-Fabric-3#357]
**Is this a modpack or mod issue?**
This is a modpack issue due to pertaining to the quests created by the team.

**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**
Updated:
- *Bewitchment* to version 10
- *Pehkui* to version 2.0.0
- *Fabric API* to version 0.34.1
- *Cardinal Components API* to version 2.8.2
- *Better End* to version 0.9.6 pre
- *Modern Industrialization* to version 0.3.17

Added:
- *Better Nether* version 5.0.5
- *Enhanced Block Entities* version 0.3.1
- *Enhanced Mushrooms* version 1.0.4

**Modpack Version**
2.7.2

**Describe the bug**
The following grammar errors were found in the new quests that are live on the NA server:
- "Sandwhichable," should be *Sandwichable* (fixed spelling)
![2021-05-08_15 39 13](https://user-images.githubusercontent.com/69029346/117555504-9de81800-b014-11eb-9b59-c489ba800aad.png)
- "Twighlight valley," should be *Twilight Valley* (fixed spelling and capitalization)
![2021-05-08_15 39 19](https://user-images.githubusercontent.com/69029346/117555513-b821f600-b014-11eb-83fd-131ff8a59a81.png)
- "Stone forest," should be *Stone Forest* (fixed capitalization)
![2021-05-08_15 48 04](https://user-images.githubusercontent.com/69029346/117555534-ec95b200-b014-11eb-963f-76adc99b8baf.png)
- Namespace id's for End biomes, should be names like the other biome quests
(The below applies to all of the quests in this category, not just the one pictured)
![2021-05-08_15 39 34](https://user-images.githubusercontent.com/69029346/117555543-fae3ce00-b014-11eb-8603-6f2f66b7ea0f.png)

**To Reproduce**
1. Examine the above quests in the quests menu on the NA server. They are not in the release version of the pack, so they will not appear in single player.

**Expected behavior**
These grammar errors would not exist.

**Comment by frogies44** [comment]
Fixed
