### ISSUE TITLE
[BUG] Chapter 2 Tech Reborn locked

### ISSUE THREAD

**Issue by Orlefanto** [TeamAOF/All-of-Fabric-3#359]
Hello! Original modpack version is 2.1.3hotfix without any changes.
I complete first chapter "Kibe". With cheats. But next chapter Tech Reborn still locked.

[
![Screenshot 2021-05-10 161459](https://user-images.githubusercontent.com/13574693/117664948-02d57680-b1ab-11eb-93b6-fafbec32fba7.jpg)
](url)

[
![Screenshot 2021-05-10 161721](https://user-images.githubusercontent.com/13574693/117665164-3c0de680-b1ab-11eb-80e6-8ba5e3c03a54.jpg)
](url)

**Comment by ImAK9** [comment]
Pack version is very outdated, update the pack.
