### ISSUE TITLE
Modular Armor is uncraftable.

### ISSUE THREAD

**Issue by siriusbtyt** [TeamAOF/All-of-Fabric-3#36]
[Warning: I am running version 1.4.1 but looking at the changelogs it's not fixed but this is just in case.]
The steel armor from Industrial Revolution is uncraftable and if you use the one from Astromine, it doesn't work.

*Clicked the steel armor for looking at the craft*
![image](https://user-images.githubusercontent.com/60975935/89165721-3ed30f80-d579-11ea-900d-0b714baf609d.png)

**Comment by siriusbtyt** [comment]
Also is there even a wiki for this mod ? I can't find it anywhere...

**Comment by siriusbtyt** [comment]
Not craftable in 1.5.1 too.

**Comment by Monster-Zer0** [comment]
This is a bug in industrial revolution that will be fixed in an upcoming update of theirs.
