### ISSUE TITLE
[BUG] Version not working

### ISSUE THREAD

**Issue by xTheEpicGamerx** [TeamAOF/All-of-Fabric-3#376]
**Is this a modpack or mod issue?**
(if something is screwy using a certain mod, then send the bug to the mod dev first.)

**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**
I have not added any mods, and when I do open the mods folder nothing shows up.

**Modpack Version**
(any bugs using a non-up-to-date version will be asked to replicate with the most up-to-date release)
I am using the newest version (3

**Describe the bug**

**To Reproduce**
1. Go to 'curseforge launcher go to all the fabric 3'
2. Click on 'Play'

**Expected behavior**
Pressing play will not load the game but instead bring up an error saying "Could Not verify Minecraft Version"

**Screenshots**
![Screen Shot 2021-05-24 at 8 21 46 AM](https://user-images.githubusercontent.com/84683430/119355159-8e024200-bc6a-11eb-8f49-b591878a8a08.png)

**Logs**
No logs needed

**Additional context**
I am very new to GitHub tell me if I need to improve on something

**Comment by irunatbullets** [comment]
I'm unable to reproduce this. Are you able to try creating a new instance of the pack? 

If that still doesn't work I usually recommend [gdlauncher ](https://gdevs.io/) for fabric modpacks because it very rarely messes up installs.

**Comment by xTheEpicGamerx** [comment]
Uh let me try that

**Comment by xTheEpicGamerx** [comment]
Oh cool, it worked, I made a duplicate It, thanks!
