### ISSUE TITLE
Battle towers key fail

### ISSUE THREAD

**Issue by 20557023bpenstone** [TeamAOF/All-of-Fabric-3#377]
Battle towers fails to spawn 10 battle keys in the tower for spawning boss

**Comment by irunatbullets** [comment]
Just wanting to get a bit more information about this so I can try to reproduce it.
- Which version of the pack were you using?
- How many mob spawners were in the tower
- Did you use any item in particular to break those spawners?

**Comment by 20557023bpenstone** [comment]
I wasn't breaking the spawners.. my bad hahaha
