### ISSUE TITLE
Do i need to change worl generation type?

### ISSUE THREAD

**Issue by djcheesus** [TeamAOF/All-of-Fabric-3#378]
Just wondering do I need to change the world gen type on my server when loading this pack? 

Thanks,
DJ_Cheesus

**Comment by xTheEpicGamerx** [comment]
I don't think you would need too,  no but Im not sure of it you should make a test world maybe

**Comment by irunatbullets** [comment]
Default gives you all of the modded biomes.

Simplex and Ecotones are alternate terrain generation - they're both pretty neat.
