### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Nekohime89** [TeamAOF/All-of-Fabric-3#387]
I swapped out lithium for optifine (latest version) and optifabric. and it crashes the game.

edit: added crash log
[latest.log](https://github.com/TeamAOF/All-of-Fabric-3/files/6564760/latest.log)

**Comment by szumaster** [comment]
You got tutorial on official AOF discord. Please check that before creating the issue ticket.

**Comment by CammiePone** [comment]
Okay, so... you swap out the _server-side_ (TPS) performance mod that generally works fine with other mods for the _client side_ (FPS) performance mod that generally fucks up other mods.

If you want a specific shaderpack, just use Iris and the compatible version of Sodium. If you just want shaders in general, take a look at Canvas. If all you want is client-side performance, Sodium does it better and doesn't screw up other mods in the process.

**Comment by irunatbullets** [comment]
Given that optifine is no longer compatible with the pack and we recommend using iris for shader support, I'm closing this issue.
