### ISSUE TITLE
[BUG] Mod mismatch between modpack an ds

### ISSUE THREAD

**Issue by JulianVennen** [TeamAOF/All-of-Fabric-3#392]
**Is this a modpack or mod issue?**
Modpack

**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**
No

**Modpack Version**
2.8.1

**Describe the bug**
When I install the latest server pack and try to join the server I get the Error "Registry remapping failed: Recieved ID map for Minecraft:sound_event contains IDs unknown to the receiver!" 

**To Reproduce**
1. Download the modpack
2. Download the server pack
3. Run server starter to install the mods and start the server
4. try to join
5. see the error message

**Screenshots**
https://img.steinh.art/KuNOLPs.png

**Logs**
Client: https://paste.alloffabric.com/osomilomod.yaml
Server: https://paste.alloffabric.com/ibanisomom.yaml

**Comment by Monster-Zer0** [comment]
Your client and server version are not the same. Make sure both are running the same version of AOF. This is literally the problem.. so please double.. triple check everything.

**Comment by JulianVennen** [comment]
I had already double checked that by reinstalling it.
I imported the zip manually and that seemed to work
