### ISSUE TITLE
[Question] Turn off the mini-map in 2.8.2

### ISSUE THREAD

**Issue by duncanwebb** [TeamAOF/All-of-Fabric-3#400]
Which mod is responsible for the mini-map in version 2.8.2?

**Comment by Fool-Ish** [comment]
I have been having an issue in a server where the minimap does not show up. I believe the mod responsible is FTB Chunks. I was looking through the mods and it doesn't even look like that mod is in my server files so that might be what is causing any problems for you as well.

**Comment by duncanwebb** [comment]
Normally, mini-maps are client mods only, but I could be wrong. My problem is that it is not poor.

**Comment by Monster-Zer0** [comment]
Ftb chunks is required by ftb teams.. which is required by ftb quests. Idk what else to mention here. Ftb chunks is the minimap.. but get rid of it and you'll have to not have quests.

**Comment by duncanwebb** [comment]
I see, many thanks. It can be disabled from the settings menu.

**Comment by irunatbullets** [comment]
Seems to be resolved, if not feel free to reopen.
