### ISSUE TITLE
Replace CC: Restitched with CC: Restitched Updated for the time being

### ISSUE THREAD

**Issue by imreallybadatnames** [TeamAOF/All-of-Fabric-3#405]
CC: Restitched is currently being unmaintained and some users are beginning to notice some issues with it. CC: Restitched Updated is a fork of CC: Restitched which is more actively maintained, updated to the latest version(not just compat from 1.16.2), and fixes all the issues which players encounter in CC: Restitched.

The replacement should not break existing things in worlds which have the old CC: Restitched stuff in it.

**Comment by imreallybadatnames** [comment]
(curseforge link: https://www.curseforge.com/minecraft/mc-mods/cc-restitched-updated)

**Comment by dandin87** [comment]
This is already the version in the pack.....

**Comment by Merith-TK** [comment]
Yep, CC:RU has its mod.json releases labeled as CC:Restitched, Zundrel's CC:R has its mod.json releases labeled "CC:Tweaked for Fabric"
