### ISSUE TITLE
[BUG] Tools not available for crafting

### ISSUE THREAD

**Issue by Hallowskeloton** [TeamAOF/All-of-Fabric-3#408]
**Is this a modpack or mod issue?**
(if something is screwy using a certain mod, then send the bug to the mod dev first.)
Modpack issue mods work fine on their own
**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**

**Modpack Version**
(any bugs using a non-up-to-date version will be asked to replicate with the most up-to-date release)
2.8.2

**Describe the bug**
When going to craft certain vanilla hammers like the obsidian one and emerald  or the sapphire and peridot tools it dosen't allow me to craft them or use them
**To Reproduce**
1. Go to 'crafting table or jei'
2. Click on 'obsidian hammer or peridot sword"

**Expected behavior**
being able to craft them
**Screenshots**

**Logs**
(you can use https://paste.alloffabric.com)

**Additional context**

**Comment by dandin87** [comment]
These are intentional disabled. Obsidian hammer has insane durability and the tech reborn tool also have far too much durability. We do not feel the need to have every possible ore/gem have tools/armor either.
