### ISSUE TITLE
I can't install Optifine

### ISSUE THREAD

**Issue by Orlefanto** [TeamAOF/All-of-Fabric-3#424]
Hi! I can't install Optifine, please help me!
I try to copy OptiFine HD U G8 in mods folder, start the game and... nothing :-( No Optifine in settings and mods. Game version is 2.8.5

**Comment by dandin87** [comment]
For starters you would also need Optifabric, However Optifabric/Optifine is incompatible with the modpack. I would recommend using Iris and Indium instead. Iris is a GLSL (Optifine) Shaders mod and comes with Sodium, and Indium adds Fabric Rendering API to Sodium, which is required to allow Sodium to work with the pack.
https://www.curseforge.com/minecraft/mc-mods/irisshaders 
https://github.com/comp500/Indium/actions/runs/923502396

**Comment by Orlefanto** [comment]
Optifine/Optifabric work incorrectly with mods AE2 and Industrial Revolution, but with Iris and Sodium no bugs with these mods! 
Thank you!

**Comment by Orlefanto** [comment]
And another problem - no config button for shaders. Is it normal for this mod?
iris-mc1.16.5-1.1.0
sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.2c3e7cc
![asdfafwerwt](https://user-images.githubusercontent.com/13574693/124915481-43f6d500-dffa-11eb-80ff-f3a132e48efa.jpg)

**Comment by Toxic-Cookie** [comment]
I have this problem too. I see that they're using shaders in the screenshots of the modpack so what gives? What's the big secret they're hiding?

**Comment by irunatbullets** [comment]
Config for shaders in iris is being worked on.

I'm closing this issue because we don't really have a desire for optifine compatibility - especially when iris with sodium/indium performs a lot better and provides shader support.
