### ISSUE TITLE
Find a tree [BUG]

### ISSUE THREAD

**Issue by AShadowedRose** [TeamAOF/All-of-Fabric-3#427]
Version 2.8.5

When I start breaking down a tree, I get a hint "Find a tree, punch it to collect wood". 
I was breaking down a Cika tree, and after a few minutes of it, the hint pops up. Does not go away. If I close out of the game and come back in, it vanishes, but then comes back again. 

I have not installed any mods. 

![Screenshot 2021-07-12 220546](https://user-images.githubusercontent.com/87354174/125394040-dcc08400-e35d-11eb-9d85-611b1101a0cf.png)

**Comment by irunatbullets** [comment]
This mod https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing/files/3011090 used to be in the pack, but I don't see any information about why it was removed (perhaps by mistake?).

You can either add that mod back in, or you can edit your `options.txt` like so
```
tutorialStep:none
```
