### ISSUE TITLE
Proposal to change the default config for roughly enough items

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#43]
#### I would like to propose some changes to the default config of REI:

- [ ] `slotlink` has a very tall GUI interface and the search bar overlaps with the first row in the inventory. I made an issue https://github.com/badasintended/slotlink/issues/23, but the author told me that he won't change the interface. The easiest solution to this problem would be to move the search bar to right (`Layout > Search Field Position: Bottom Left / Right`)

- [ ] remove the default key bindings for `Show Recipe` and `Show Uses` or change them to something that cannot be activated while typing (`ctrl + r` and `ctrl + u`). The current behavior is very annoying, because REI is visible in all interfaces and when you type a text containing `r` or `u` the keybindings trigger and you have to start typing all over again. (why would you need those bindings at all, when you can simply right/left-click the items in REI?)

- [ ] Disable `Search Filter in Favorites` (this is disabled by default in just enough items) (`Advanced > Search > Search Filter in Favorites`)

#### Why don't I change this locally?

Every time a new update is released the config file is overwritten and I have to configure rei again.

**Comment by Monster-Zer0** [comment]
added for 2.0 dev
