### ISSUE TITLE
Use Your Options Shall Be Respected

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#44]
https://www.curseforge.com/minecraft/mc-mods/your-options-shall-be-respected-yosbr

**Comment by calloatti** [comment]
What would be the use case for this? When you are installing/importing a modpack zip you are creating a new instance.

**Comment by Luro02** [comment]
Yes, but I would like to keep the config from my old instance, so I copy the `options.txt` and overwrite the new config folder with the old folder. (This can cause problems if an update changed existing config files).

**Comment by Monster-Zer0** [comment]
testing for 2.0 dev
