### ISSUE TITLE
Tridents unable to be enchanted with Loyalty

### ISSUE THREAD

**Issue by gaypineapplez** [TeamAOF/All-of-Fabric-3#45]
I found a trident in an underwater mineshaft that was pre-enchanted with riptide. even after removing all enchants with a grinding wheel, Loyalty could not be applied from a book that had loyalty 3. I am still running 1.4.2 but did not see any fixes

**Comment by Monster-Zer0** [comment]
we probably wouldn't do a fix for that. it's most likely a mod that is causing this issue. maybe something to do with the loot tables.
