### ISSUE TITLE
I can't login to my own local server

### ISSUE THREAD

**Issue by Orlefanto** [TeamAOF/All-of-Fabric-3#461]
Hi! I can't login to my local server. Please, help me!

Error text:
internal exception: io.netty.handler.codec.decoderexception: badly compressed packet - size of 2843035 is larger than protocol maximum of 2097152

2.8.8  server version
1.16.5 mnecraft

Java:
jre1.8.0_321
jdk-17.0.2

Minecraft:
2 PC:
1) Iris fabric loader 0.11.5-1.16.5
2) Fabric 1.16.5

**Comment by Monster-Zer0** [comment]
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric

add xl packets

should go on both server and client
