### ISSUE TITLE
Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by Seegras** [TeamAOF/All-of-Fabric-3#47]
Since the latest update today, I get these, by doing seemingly random things:
- mining a certain block
- opening a certain chest
- breaking the same chest: 

(not really sure how to format this usefully; also I added worldedit here, but the same happens without)
`---- Minecraft Crash Report ----

Time: 8/7/20 7:17 PM
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_2248.method_9576(class_2248.java:469)
	at net.minecraft.class_3225.method_14266(class_3225.java:248)
	at net.minecraft.class_3225.method_21717(class_3225.java:222)
	at net.minecraft.class_3225.method_14263(class_3225.java:197)
	at net.minecraft.class_3244.method_12066(class_3244.java:944)
	at net.minecraft.class_2846.method_12361(class_2846.java:40)
	at net.minecraft.class_2846.method_11054(class_2846.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [astromine.mixins.json:PiglinBrainMixin] from phase [DEFAULT] in config [astromine.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 27 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE_ASSIGN") on net/minecraft/class_4838::wearsGoldArmorInject with priority 1000 cannot inject into net/minecraft/class_4838::method_24719(Lnet/minecraft/class_1309;)Z merged by net.piglintag.mixin.PiglinBrainMixin with priority 1000 [PREINJECT Applicator Phase -> astromine.mixins.json:PiglinBrainMixin -> Prepare Injections ->  -> handler$zkh000$wearsGoldArmorInject(Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/lang/Iterable;Ljava/util/Iterator;Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:367)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1244)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.7.12
	Java Version: 1.8.0_252, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Debian
	Memory: 2206373216 bytes (2104 MB) / 3867672576 bytes (3688 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.10.0+1.16.1
		advancements-enlarger: Advancements Enlarger 0.2.2
		adventurez: AdventureZ 1.0.7
		amecsapi: Amecs API 1.0.2+1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.0+1.16-rc1
		astromine: Astromine 1.5.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bambootweaks: Bamboo Tweaks unspecified
		bebooks: Better Enchanted Books 1.1.1
		bedspreads: Bedspreads 1.0.0-1.16.1
		bettergraves: Better Graves 0.3.0
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson +
		boringbackgrounds: Boring Backgrounds 2.1.0-1.16.pre3
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		campanion: Campanion 1.1.13+build.35
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cavebiomes: Cave Biomes 0.2.4
		chainmail: Chainmail 0.3.0
		cherishedworlds: Cherished Worlds 1.0.1-1.16.1
		chunkpregen: Fabric Chunk Pregenerator 0.2.2
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.0.7
		cloth-armor-api-v1: Cloth Armor API v1 1.0.7
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.7
		cloth-common-events-v1: Cloth Common Events v1 1.0.7
		cloth-config2: Cloth Config v4 4.6.0
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.7
		cloth-scissors-api-v1: Cloth Scissors API v1 1.0.7
		cloth-utils-v1: Cloth Utils v1 1.0.7
		coderecipes: Programmatic Recipes 0.3.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.2.0
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		craftable_utilities: Craftable Utilities 1.0.1
		craftpresence: CraftPresence 1.6.6
		creativebuttonmover: Creative Button Mover 0.2.5
		crookedcrooks: Crooked Crooks 1.2.1+1.16.1
		crusade: Crudade Mod 1.1.2
		dankstorage: Dank Storage 1.1c_1.16.1
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		dishes: Delicious Dishes 1.0.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.2.0-beta1
		dynamicfps: Dynamic FPS 1.1.4
		dynocaps: DynoCaps 1.1.1
		ecotones: Ecotones 0.5.1
		eggtab: Egg Tab 1.2.0+1.16-fabric
		endreborn: End: Rebellion 1.6
		expandedstorage: ExpandedStorage 5.3.16
		experimentaway: ExperimentAway 1.0.0
		ezpas: Ezpas 1.0.4
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		flesh2leather: Flesh2Leather 1.0.0
		flonters: Flonters 1.1.0+1.16.1
		flora-doubling: Flora Doubling 1.1.2
		gameinfo: GameInfo 2.0.0a-experimental-06 1.16.1
		givemehats: Give Me Hats! 1.2.8
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		golemsgalore: Golems Galore 0.1.4+mc.1.16.1
		hard-hat-steve: Hard Hat Steve 1.1.1
		harvest: Harvest 1.2.12
		healthoverlay: Health Overlay 3.6.12
		horseinfo: Horse Info 0.2.2-1.16.1
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		improved-stations: Improved Stations 2.0.2-unstable
		indrev: Industrial Revolution 1.4.9-BETA
		inmis: Inmis 1.2.0-1.16.1
		intotheomega: Into the Omega 1.0.1-beta-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.0+j1.2.0
		jumploader: Jumploader 2.0.1
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.1.12-BETA
		ktdatataglib: KtDataTagLib 1.3.4
		kubejs: KubeJS 1.1.2
		kyrptconfig: Kytpt Config 1.1.0-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.2.0+1.16.1
		library_of_exile: Library of Exile 1.0.1
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.4.1
		linkart: Linkart unspecified
		linkedstorage: Linked Storage 1.3.5-1.16
		lithium: Lithium 0.5.1
		magna: Magna 1.3.2-1.16.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		mo_glass: Mo Glass 1.3-MC1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		moreberries: More Berries 1.3.1
		morepaths: More Paths 0.0.2
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		mousewheelie: Mouse Wheelie 1.5.0+mc1.16.1
		netheritehorsearmor: Netherite Horse Armor 0.4.0+1.16.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		notes: Notes 1.0.1
		okzoomer: Ok Zoomer 4.0.0-alpha.5+1.16.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		p3utils: P3NG00's Utilities 0.0.0
		packages: Packages 1.0
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-39-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		piglintag: PiglinTag 1.0.0
		playerabilitylib: Pal 1.2.0
		quickshulker: Quick Shulker 1.1.5-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.4+build.64
		repurposed_structures: Repurposed Structures 1.4.1
		respawnablepets: Respawnable Pets 4
		ringsofascension: Rings of Ascension 1.0.5
		riverredux: River Redux 0.1.4
		roughlyenoughitems: Roughly Enough Items 4.10.5
		roughlyenoughresources: Roughly Enough Resources 2.0.2
		sandwichable: Sandwichable 1.1.1-snapshot
		secretrooms: Secret Rooms 0.9.1+1.16.1
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		simpledrawers: Simple Drawers 1.8.0-1.16.1
		simpleteleporters: Simple Teleporters 2.2.0
		simplevoidworld: Simple Void World 4.0.0
		simplexterrain: Simplex Terrain 0.6.5
		slabhelper: Slab Helper 1.3.1
		slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
		slotlink: slotlink 1.0.3+minecraft-1.16.1
		smoothbedrock: Smooth Bedrock (Fabric) 1.2.3
		soulbound: Soulbound 1.0.1
		spinnery: Spinnery 3.1.13
		staffofbuilding: Staff of Building 1.2.0-1.16
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structure-helpers: Structure Helpers 2.1.0
		structurized: Structurized 1.0.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 2.2.14+build.28
		trinkets: Trinkets 2.6.3
		tweed: Tweed API 3.0.0-beta.9
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 2.0.3-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		woods_and_mires: Woods and Mires 1.0.0+1.16.1
		worldedit: WorldEdit 7.2.0-beta-02+d10d7d6
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.19.0
		xaeroworldmap: Xaero's World Map 1.9.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['Seegras1'/198, l='ServerLevel[AOF3]', x=-52.53, y=77.00, z=69.66]]
	Data Packs: vanilla (incompatible), fabric/crusade, fabric/iron-jetpacks, fabric/kibe (incompatible), fabric/adabraniummod, fabric/villagerhats, fabric/mo_glass, fabric/techreborn, fabric/improved-stations, fabric/fabric-tool-attribute-api-v1, fabric/blockus, fabric/hard-hat-steve (incompatible), fabric/trapexpansion, fabric/expandedstorage, fabric/dishes, fabric/golemsgalore, fabric/linkedstorage, fabric/simpleteleporters, fabric/simplevoidworld, fabric/campanion, fabric/sandwichable, fabric/ecotones, fabric/traverse, fabric/winged, fabric/inmis, linkedstorage:enderstorage, fabric/adorn, fabric/bunch-o-trinkets, fabric/flora-doubling, fabric/glassdoor, fabric/libcd, fabric/secretrooms, fabric/staffofbuilding, fabric/vanilla-hammers, fabric/wolveswitharmor, secretrooms:server_pack, fabric/astromine, fabric/bambootweaks, fabric/cinderscapes, fabric/cotton-commons, fabric/fabric-furnaces, fabric/flonters, fabric/glassential, fabric/harvest, fabric/linkart, fabric/moreberries, fabric/morepaths, fabric/mostructures, fabric/packages, fabric/simpledrawers, fabric/slotlink, fabric/tacocraft, fabric/terrestria, fabric/woods_and_mires, fabric/crookedcrooks, fabric/endreborn, fabric/flesh2leather, fabric/repurposed_structures, fabric/adventurez, fabric/compressedblocks, fabric/indrev, fabric/piglintag, fabric/respawnablepets, fabric/vanillaexcavators, fabric/dml-refabricated, fabric/ezpas, fabric/intotheomega, fabric/netheritehorsearmor, fabric/slabhelper, fabric/bedspreads, fabric/craftable_utilities (incompatible), fabric/dankstorage (incompatible), fabric/structure-helpers
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'`

**Comment by Shnupbups** [comment]
Update to the latest version of the pack.
