### ISSUE TITLE
Game crashes when entered nether

### ISSUE THREAD

**Issue by echooff2** [TeamAOF/All-of-Fabric-3#48]
When I entered nether, server crashed. Log: https://echooff.pl/crashlog.txt .

**Comment by Shnupbups** [comment]
Try updating to the latest pack version, it might help.
That log is rather strange though.

**Comment by echooff2** [comment]
I updated to 1.5.2a and no longer crashes so so i am closing this. Weird log probably because it is server and server timed out ( processing 1 tick took over 60 seconds)
