### ISSUE TITLE
Crash when placing astromine block breaker

### ISSUE THREAD

**Issue by cncz42** [TeamAOF/All-of-Fabric-3#49]
As the title says, the game crashes when placing theblock breaker added by astromine, not sure if this is a modpack issue or an astromine issue

**Comment by BlueskyClouds** [comment]
The astromine mod is still being updated and is not complete. This issue has been fixed in the latest version. It is best to avoid using this mod content

**Comment by AK9Official** [comment]
Fixed for 2.0
