### ISSUE TITLE
Game Crash When Firing Bow.

### ISSUE THREAD

**Issue by chendapped** [TeamAOF/All-of-Fabric-3#51]
When right-clicking to fire bow game will crash. Just tested and verified issue occurs when offhand is empty as im usually carrying something in the off hand. 
[crash-2020-08-09_08.31.29-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5047492/crash-2020-08-09_08.31.29-client.txt)
[crash-2020-08-09_08.35.15-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5047493/crash-2020-08-09_08.35.15-client.txt)

**Comment by AK9Official** [comment]
Update to 1.5.3

**Comment by chendapped** [comment]
Thanks, didnt see the new update. Issue is resolved. Thanks for the great work on the mod pack. Running AOF at 150 fps where other 1.16 mod packs my pc with ryzen 7 and 32 gb of ram can barely push 50.
