### ISSUE TITLE
[1.5.3] Mod (310111) removed from CurseForge - Installation in Twitch fails

### ISSUE THREAD

**Issue by TigerWalts** [TeamAOF/All-of-Fabric-3#52]
The mod with Project ID `310111` appears to have been removed completely from CurseForge. Even the API says it doesn't exist, which also means I can't tell which mod it is.

This is causing installations in Twitch to fail.

**Comment by BlueskyClouds** [comment]
https://minecraft.curseforge.com/projects/310111/files/3023344/download

**Comment by BlueskyClouds** [comment]
maybe it's your network problem

**Comment by TigerWalts** [comment]
How odd, it failed on my PC and a remote machine too. Must have been hitting an old cache.

Working now. I'll close the issue.

**Comment by calloatti** [comment]
The CF API has been having issues for the last couple of days. That is the source of this problem. It has been failing to return  data for some mods, returning incomplete data, and just failing with 404s.
