### ISSUE TITLE
Diggus Maximus (vein miner) keybinding ??

### ISSUE THREAD

**Issue by morahlaura** [TeamAOF/All-of-Fabric-3#53]
Hi, 

This is the first time I'm using Fabric mods and so far I'm pretty impressed. 

However I'm having trouble with the Diggus Maximus keybinding. 

The mod page says it binds to "~" by default (really " ` " on an American keyboard I assume) but in straight-out-of-the box AOF3 this does something with the Slab Helper mod. Diggus keybiding doesn't show up in the Controls list so I removed the Slab Helper key bind, but no vein mining.

Tried launching AOF3 without loading Slab Helper (I use MultiMC). Still no vein mining.

Is this disabled in a config somewhere? I'm not afraid to edit a config but need detailed directions. 

Am I doing something wrong? I'm used to 1.12.2 modpacks where you hold down the ` key while mining and it mines everything of like block (eg the whole oak tree or all 6 blocks of coal in a wall). 

Any idea what the deal is?

Thanks in advance,
MorahLaura

**Comment by Daniel13265** [comment]
It has been bond to "button 4" instead of "~" by default in AOF3. You can rebind it in Mod Menu.

**Comment by morahlaura** [comment]
Thanks!!    ...   What's button 4??

**Comment by coiledmocha** [comment]
Some button on the mouse not everyone has I believe.

**Comment by Monster-Zer0** [comment]
fixed in 2.0
