### ISSUE TITLE
Crash whenever opening a container in a village (Chest, Barrel) 

### ISSUE THREAD

**Issue by Scarlette564** [TeamAOF/All-of-Fabric-3#56]
Whenever I open a container in a village my game crashes. The only mod I have added is Sodium. The crash log is included below.

[crash-2020-08-18_15.02.28-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5092345/crash-2020-08-18_15.02.28-server.txt)

**Comment by AK9Official** [comment]
Update to 1.5.3

**Comment by Scarlette564** [comment]
Is it available in zip for MultiMc?

**Comment by Scarlette564** [comment]
Updated to 1.5.3, issue fixed. I somehow downloaded 1.5.2 instead before. Closing Issue.
