### ISSUE TITLE
Roughly Enough Resources overworld generation isn't available

### ISSUE THREAD

**Issue by Meridian117** [TeamAOF/All-of-Fabric-3#63]
I've been trying to locate where certain ores spawn, and I found out that RER was supposed to provide a spawn location graph once some chunks had been loaded.  However, I cannot find the tab for that anywhere, regardless of what ore or item I attempt to locate.  Do I need to re-install, or is this not functioning in 1.16.1?

**Comment by Animaly0** [comment]
I have the same problem with the 1.5.3 version of the modpack, I can find the nether ressouces but nothing for the Overworld

**Comment by Meridian117** [comment]
I have used both r and u.  It brings up crafting and block drop, but not overworld tab

**Comment by Monster-Zer0** [comment]
I can not reproduce this. you can tell if rer has done it's thing by going into your world folder then to data.

there should be a rer_worldgen.dat

if there isn't, then for some odd reason your world never had the genning when you created it and continues to not update. you can try to pregen with

https://www.curseforge.com/minecraft/mc-mods/chunk-pregenerator-fabric

which should populate things.

however.. this is most likely is an RER issue. so you might have better luck discussing it over there.

https://github.com/theorbtwo/RoughlyEnoughResources/issues

**Comment by Animaly0** [comment]
Just for letting you know, there is indeed no rer_worldgen.dat file in DIM1 but there's one in DIM-1.
pregen didn't fix the issue, i'll try posting an issue RER github

**Comment by Meridian117** [comment]
Thanks for the help Monster-Zer0 and Animaly0.  I really appreciate this, I think I'll head over to rer github and see if anything has changed :D
