### ISSUE TITLE
Sounds don't work

### ISSUE THREAD

**Issue by amadeus06** [TeamAOF/All-of-Fabric-3#64]
I can only hear the biomes sounds. Wind howling,beach sounds that sort of stuff. However I cannot hear any other sound. So i can't hear my feet moving on the ground or the breaking of blocks, creepers blowing up behind me nothing. Not sure how to fix.

**Comment by Monster-Zer0** [comment]
ummm, neither do I.

would help to have

java version
operating system

**Comment by 5L4M** [comment]
This happened to me on the latest (Mac) version available on Twitch... it seemed the vanilla sound files were missing in the install... (it did have the modded sound files for the ambient noises etc)... downloaded them separately from Curse forum and threw in resources folder and all worked fine....

**Comment by amadeus06** [comment]
I am on a Mac. Im using the latest version available on Twitch. I suspect maybe what 5L4M is describing is the issue. 5l4m, do you have a link to the files you added to the resources folder.

**Comment by 5L4M** [comment]
https://www.curseforge.com/minecraft/texture-packs/minecraft-resource-pack-template/files/2982799

this is the one I used... put in resource folder then enable in game (resource packs) I placed it 2nd down in list...

Hope it helps

**Comment by amadeus06** [comment]
I forgot to reply, but this resource pack solved the problem

**Comment by blakdragan7** [comment]
if you are still having this problem in version 2.1.1 like I am then the new resource pack to use is this one
https://www.curseforge.com/minecraft/texture-packs/minecraft-resource-pack-template/files/3029942
