### ISSUE TITLE
1 Frame per Minute in existing worlds, runs fine in new world for 5 mins

### ISSUE THREAD

**Issue by harby1** [TeamAOF/All-of-Fabric-3#65]
Basically as in the title, i was running the latest release version but am currently rolling back to see if i can remedy it in the short term. Havent updated anything, windows, java, vanilla, the launcher etc. Logged out night before last and have been unable to play since logging on again the next day, PC wasnt even powered off. Confused lol :)

**Comment by Monster-Zer0** [comment]
how is the disk space?

**Comment by harby1** [comment]
> how is the disk space?

I've just checked this and while it shouldn't be an issue, twitch was installing instances to my C drive. Still had 45gb free but I will report if moving everyone to my storage drive solves it. Thanks for the response! 🙂

**Comment by harby1** [comment]
Seems the SSD with Windows on it was failing, as to why it manifest itself specifically in this pack of MC i do not know. New drive and im back to the grind 😊
