### ISSUE TITLE
Day not shown for GameInfo on Server

### ISSUE THREAD

**Issue by kvgeorge1** [TeamAOF/All-of-Fabric-3#66]
When using GameInfo for AOF3, the "Day" is not shown in the HUD when played on a server.  This works just find when playing single-player.

**Comment by Monster-Zer0** [comment]
I believe you just have to hit "i" to change the view

**Comment by kvgeorge1** [comment]
“i” just hides/shows the HUD.  This has to do with MUTLIPLAYER worlds and not SINGLEPLAYER worlds.

**Comment by kvgeorge1** [comment]
After doing some research, this may be related to a bug that was fixed in 1.5.4 of the mod.  However, AOF3 uses an "alpha" version of 2.0 for 1.16.1 of fabric.  Maybe the bug was re-introduced?

In any event, there is a 1.5.4 version for 1.16.2. Are there any plans to update AOF3 to 1.16.2?

**Comment by Monster-Zer0** [comment]
we do not have an alpha version of 2.0 for 1.16.1
we do not have a 1.5.4 version for 1.16.2

we are currently working on 2.0 for 1.16.2

**Comment by kvgeorge1** [comment]
Wait – I don’t understand.  When I look at the mods for AOF3, Gameinfo-mod-2.0.0a-experimental-06 1.16.1.jar is in the mod folder where I installed the pack.  What version should it be?

 

Also, I am using GDLauncher that downloaded the pack from curseforge.

**Comment by Monster-Zer0** [comment]
oh, you are talking gameinfo. not aof3.

not sure about the bug. I notice it in aof3 2.0 (in development)

it must just be an issue with gameinfo it's self.. maybe the client side can't pull the server side day info.. which is silly
