### ISSUE TITLE
World gen is weird

### ISSUE THREAD

**Issue by Thanoid1** [TeamAOF/All-of-Fabric-3#67]
I just downloaded the mod pack using the twitch launcher and was eager to play, when i created a new world i was stuck in some blocks and I fell through a bunch more. So I flew up with creative mode and saw this at the top.
![2020-08-24_16 23 56](https://user-images.githubusercontent.com/70173130/91092856-a0414800-e626-11ea-8d72-efad7db02319.png)

**Comment by Thanoid1** [comment]
I also created multiple new worlds and this issue was the same.

**Comment by Thanoid1** [comment]
Same thing but with proof. 
[https://www.kapwing.com/videos/5f4426445e922200159a9131](url)

**Comment by Thanoid1** [comment]
[https://www.kapwing.com/videos/5f4426445e922200159a9131](url)

**Comment by Thanoid1** [comment]
[https://gyazo.com/9f19c5578ebee126a8ae28c2da24fa2f](url)

**Comment by Thanoid1** [comment]
It keeps happening https://gyazo.com/787b0dcb09915eb00666b1dc652b3ee7

**Comment by Monster-Zer0** [comment]
have you tried different worlds? ie terrain gen?

**Comment by Thanoid1** [comment]
I have created about 7 worlds and the same thing keeps happening. Where i load in, and after 30 seconds a visual glitch or terrain glitch happens.

**Comment by Monster-Zer0** [comment]
ok, but have you chose a different world gen?

**Comment by Thanoid1** [comment]
I have only tried it with default terrain gen.

**Comment by Thanoid1** [comment]
Sorry and also ecotones.

**Comment by Thanoid1** [comment]
I have tried all the world gen but the same thing keeps happening.

**Comment by Monster-Zer0** [comment]
got any logs? ones that include activity of this visual glitch.

please post to something like hastebin or pastebin.

**Comment by Thanoid1** [comment]
It doesn't crash or make any logs so i don’t know

**Comment by Monster-Zer0** [comment]
check the logs folder in your minecraft instance

**Comment by Thanoid1** [comment]
I just solved the issue, it was because i had sodium installed. So i just deleted it. Thanks for your help anyways.
