### ISSUE TITLE
Recipe/REI issue with some astromine stuff

### ISSUE THREAD

**Issue by MattBee2k2** [TeamAOF/All-of-Fabric-3#69]
When trying to craft some of the hammers from astromine such as the silver hammer. It only accepts astromine ingots whereas some of the others accept ingots from tech reborn or astromine so not sure if this was a mistake.

One other thing is that several of the astromine ingots don't have a recipe in the JEI telling you what converts into the ingots so they seem unachievable.

Thanks.

**Comment by Monster-Zer0** [comment]
astromine has fixed a lot since 1.5.3 of aof3

i'll test this and update if I added recipe's or not.

**Comment by MattBee2k2** [comment]
> astromine has fixed a lot since 1.5.3 of aof3
> 
> i'll test this and update if I added recipe's or not.

I see, appreciate it and look forward to future updates.
