### ISSUE TITLE
End Portal not existing

### ISSUE THREAD

**Issue by xBvrgx** [TeamAOF/All-of-Fabric-3#72]
Is there possibility to go to the End? I tried several worlds but for me Strongholds are not generating with portals.

**Comment by Monster-Zer0** [comment]
yes, it's possible.

not sure what terrain gen you are using. but I can't reproduce using default.

**Comment by Monster-Zer0** [comment]
still issue in latest?

**Comment by Wolfynridge** [comment]
I also have this issue, I am on a server and when I use the eye of ender when it goes down to the ground, it will actually end up going beneath the bedrock and the eye just goes poof. I have excavated a large area and there is no Stronghold

**Comment by jourdain77** [comment]
I have this the same issue, although it is slightly different, I  will throw the ender eye and it will send me in a general direction, lets say this direction is dead north, the eyes will continuously send me north for 10s of thousands of blocks without ever going down, I have tried multiple worlds and I am yet to find a world that actually send me to an end portal. not sure what's happening however its good to know its not just me, any help would be greatly appreciated, thanks

**Comment by nabero** [comment]
Same issue, repurposed structures (1.8) seems to have replaced the stronghold in my case. I can /locate with the mod disabled and find the stronghold. If I go to those same coordinates with the mod enabled, another structure replaced it.

[worldgen_settings_export.json.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5374676/worldgen_settings_export.json.txt)

**Comment by nabero** [comment]
Issue still exists with latest AoF: 2.3.0 using the same worldgen settings (though it doesn't give the same world)

**Comment by dandin87** [comment]
Did you do /locate repurposedstructures:stonebrick_stronghold? because that Stronghold replaces the Vanilla one.

**Comment by nabero** [comment]
Indeed, wasn't. And ender eyes seems work in this version. Lgtm.

**Comment by AK9Official** [comment]
Fixed indev, update will be out tonight
