### ISSUE TITLE
Bug with the multi dimensional remote. 

### ISSUE THREAD

**Issue by Eisenyx** [TeamAOF/All-of-Fabric-3#77]
There is a bug with the multi dimensional remote. When I was exploring the nether, none of the things I put into my storage using the multi dimensional remote were there. They were all gone. 

Edit: I don't know if it is allowed here but here is a video link of the bug. Check the number of the logs each time. 
https://streamable.com/pan7qs

Edit 2: It also happens when doing the same thing in the end.

**Comment by Monster-Zer0** [comment]
I would report this to the slotlink author

https://github.com/badasintended/slotlink/issues
