### ISSUE TITLE
Silk touch not working

### ISSUE THREAD

**Issue by MaryHeadpoppins** [TeamAOF/All-of-Fabric-3#79]
i'm kinda retarded ngl and in previous iteration of this problem i typed mending when i meant silk touch

anyway only omega silk touch isn't working

**Comment by arun057** [comment]
Mending and silk touch dont go together. Although, an omega silk touch definitely did not work as intended for me

**Comment by MaryHeadpoppins** [comment]
normal silk touch doesn't work even without mending

**Comment by arun057** [comment]
Yep confirmed. I was wrong earlier, its fortune and silk touch that cant be together

**Comment by dandin87** [comment]
Fortune and silk touch cannot be together on purpose as a Vanilla Mechanic. Omega silk touch is broken. And I believe is not obtainable in an update to Into the Omega .

**Comment by Monster-Zer0** [comment]
into the omega is removed in 2.0

so this is a non-issue
