### ISSUE TITLE
End dimension not working on server.

### ISSUE THREAD

**Issue by Symbolicaly** [TeamAOF/All-of-Fabric-3#81]
I've downloaded All of Fabric 3 server files so my gf and I can play together. After finding the stronghold, we completed the portal and tried to go thru, but it didn't work. I went thru the server properties but there only a "Allow_nether=true" option. I added "Allow_end=true" but it didn't work. Also tried teleporting to the dimension with "exectute in minecraft:end" but it doesn't show the option aswell.

Any idea how to fix this?

Thank you!

**Comment by Monster-Zer0** [comment]
I would check permissions with your files, especially all the folders in world.

**Comment by Symbolicaly** [comment]
I checked all the folders in "world", the folder "DIM1" shows up and everything but minecraft still doesn't recognize the dimension being in the game.

Where would i check for permission?

Thank you!

**Comment by Monster-Zer0** [comment]
depends on your operating system

**Comment by Symbolicaly** [comment]
64-bit Windows Pro.

**Comment by Monster-Zer0** [comment]
oh, so I had this issue. idk what causes it. you have to add the dimensions back into the world.dat file...

ummm Idk how to explain how to do that.. you'll have to give me a bit

**Comment by Symbolicaly** [comment]
No problem, im just glad there is a solution, take your time.
