### ISSUE TITLE
Tech Reborn lead and other ingots not working for Astromine hammers

### ISSUE THREAD

**Issue by jonvonbasslake** [TeamAOF/All-of-Fabric-3#82]
I am unable to craft any of the AstroMine hammers using materials from Tech Reborn as per the image provided. 
![2020-08-30_12 26 36](https://user-images.githubusercontent.com/45696426/91655805-43c5a900-eabc-11ea-8005-2cd0c062b894.png)

I also couldn't find a way to convert between the ingots to circumvent the issue.

**Comment by Monster-Zer0** [comment]
fixed in 2.0
