### ISSUE TITLE
Quest Errors/Typos

### ISSUE THREAD

**Issue by Trouss33** [TeamAOF/All-of-Fabric-3#88]
Version: 2.0.0

I love Quests. 
Found the following.

Quest: Wtf Pocket? - Crafting task is Trash Can
Fix: Change to Trash Can on Stick

Quest: Entaglement, Make that mobfarm, and Who needs to eat anyways?,  - No reward given (ignore if intentional)
Fix: Assign reward

Quest: Magnet and Redstone Timer - Unnamed

Typos: Some
Fix: Send me the text and I can edit for correct grammar, capitalisation and punctuation.

**Comment by Monster-Zer0** [comment]
this is fixed already.

will be on the NA server when done pregenning
