### ISSUE TITLE
Polymorph crash while trying to change crafting recipe.

### ISSUE THREAD

**Issue by Topshelf2020** [TeamAOF/All-of-Fabric-3#89]
Trying to craft a wooden bucket for the Kibe intro quest crashes the client. 

https://pastebin.com/FmG48f2h

**Comment by dandin87** [comment]
Only when using Polymorph to select the bucket recipe instead of the Blockus recipe. If you use certain BYG logs then Blockus does not have a conflict. (Not sure if blockus uses any BYG logs or not, but I made the bucket just fine with Palo Verde Logs)

**Comment by AK9Official** [comment]
fixed in 2.0.1
