### ISSUE TITLE
slabhelper 1.3.3 causes crash

### ISSUE THREAD

**Issue by jingshenSN2** [TeamAOF/All-of-Fabric-3#93]
I'm the author of the slabhelper mod.  The version 1.3.3 is based on Fabric API 0.17.2. However, some function names have been changed in the new versions of Fabric API (0.19.0~0.20.1) and will cause a game crash when using half-mining mode. The latest version 1.3.4 fixed this bug. Please update this mod to version 1.3.4.
Sorry for the inconvenience I brought to your team and players because of my mistake.

**Comment by Monster-Zer0** [comment]
we will make sure to update for the next version of the modpack.

Thanks for point this out!
