### ISSUE TITLE
Being in the Nether for more then 10 minutes always ends up breaking ram-usage?

### ISSUE THREAD

**Issue by Kami-Coding** [TeamAOF/All-of-Fabric-3#94]
Whenever i spend more then about 10 minutes in the Nether i reach a point where the ram-usage suddenly goes to permanent 100% of allocated memory.

I have tested this at 8gb, 16gb, 32gb allocated and the problem is the same everytime.
I have tested this while not moving away from the netherportal and after about 6h of sleep i still sit at the same average 44% with only 8gb allocated i reach in the overworld or the end.

Adding the canvas Mod stops this issue for the Nether but also doesn't work in the overworld without crashing about once every 10 minutes while exploring the world.

Also once this problem started the excessive ram-usage won't stop until Minecraft is closed.

Hope this is fixable, thanks for looking into it.

**Comment by AK9Official** [comment]
pack version?

**Comment by Kami-Coding** [comment]
2.0.1 
i played 1.5 versions with sodium before, but its not in 1.16.2 yet

**Comment by Kami-Coding** [comment]
seems to be a rendering problem, i have seen a similiar problem happening with only a install of the "oh the biomes you'll go" and no other mods resulting in the same issue for me, but no issues on their modpage sofar

**Comment by AK9Official** [comment]
@Kami-Coding Could you test with just BYG installed?

**Comment by Kami-Coding** [comment]
gonna do soon ill update with results whenever i found the time todo so

**Comment by Kami-Coding** [comment]
oh my bad thats what i did yes...

**Comment by Kami-Coding** [comment]
also in my actual survival game i first noticed the issue i had some datapacks installed i always use from xisumavoid vanilla tweaks i need to check out if removing them makes a difference ^^
