### ISSUE TITLE
Broken Chunks with Light Level issues

### ISSUE THREAD

**Issue by TheRoboticHydra** [TeamAOF/All-of-Fabric-3#95]
Chunk having light level of 0 thus making solar panels not work in them. Placing light sources doesn't change the light level.Mobs are also able to spawn there.
![2020-09-06_11 16 55](https://user-images.githubusercontent.com/59925209/92323175-2fe9ec00-f054-11ea-9f9e-3fb2547ad22a.png)
![2020-09-06_11 17 01](https://user-images.githubusercontent.com/59925209/92323176-31b3af80-f054-11ea-973d-e2fadca1fa60.png)

**Comment by AK9Official** [comment]
Which biome is that chunk in? Also are there any structures?

**Comment by TheRoboticHydra** [comment]
Its a village in a birch forest. It seems like the 2.0.2 update fixed it

**Comment by AK9Official** [comment]
Aight glad to hear!
