### ISSUE TITLE
Quest book crash

### ISSUE THREAD

**Issue by 314resqi** [TeamAOF/All-of-Fabric-3#96]
Minecraft just crashed while i was looking into quest book.. it may by random crash..
aof3 beta 2.0.2
https://pastebin.com/6tV9WrDF

**Comment by shedaniel** [comment]
There are quests syncing issues that I am not sure how that happened, this crash indicates a bigger problem as nothing is synced to _some_ clients.

**Comment by 314resqi** [comment]
I play on "official" eu server and i am one of these affected... 0 quests and i am not member of party ...which i created.
When i joined the world quests were there but then i tryed to add one fellow to my party and it somehow broke...
