### ISSUE TITLE
Basic Coil (Jetpack) conflict with RSWires

### ISSUE THREAD

**Issue by terijaki** [TeamAOF/All-of-Fabric-3#97]
Jetpack progression is blocked due to a crafting conflict with RSWires Red Alloy Componend:
![image](https://user-images.githubusercontent.com/590522/92410715-491e9580-f145-11ea-8b92-d2cee65d7712.png)

REI recipe for Basic Coil
![image](https://user-images.githubusercontent.com/590522/92410737-55a2ee00-f145-11ea-92f9-ee18cf998033.png)

**Comment by AK9Official** [comment]
will be fixed in next update. thanks for reporting!

**Comment by craft90** [comment]
This bug returned with the latest version (2.1.2)
