### ISSUE TITLE
Enderman spawn rate is breaking everything.

### ISSUE THREAD

**Issue by SpadeCA** [TeamAOF/All-of-Fabric-3#98]
You literally can't find anything but endermen and passives. Can't progress cause I can't explore caves or farm mobs on surface cause its literally all endermen. Also causing FPS issues anywhere near a large ravine/cave system (dropping low 50's with Ryzen 5 3600x and a GTX 1650 Super). Please fix.
![2020-09-07_17 51 35](https://user-images.githubusercontent.com/11309486/92422774-63e80e80-f133-11ea-8673-e6b4b7d29e42.png)

I also tried tp'ing them all to me into a 5x5 box, not a good idea:

![2020-09-07_18 01 50](https://user-images.githubusercontent.com/11309486/92423022-4d8e8280-f134-11ea-8b42-14546e053ef2.png)

Oh no.

**Comment by Monster-Zer0** [comment]
enchanted forest.. spawns enderman. obviously too much. enchanted forest is part of BYG.

report issue to BYG https://github.com/CorgiTaco/BYG/issues
